/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness probe that also reports component versions.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ready
         * @description 200 once startup work (the gazetteer) is done, 503 before.
         */
        get: operations["ready_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/charts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chart
         * @description The birth chart: positions, houses, divisional charts, special points, Vimshottari.
         */
        post: operations["chart_v1_charts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/charts/annual": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Annual
         * @description The Tajika annual chart and Tithi Pravesha for the year after ``years_completed``.
         */
        post: operations["annual_v1_charts_annual_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/charts/dashas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Dashas
         * @description Any supported dasha system: a nakshatra dasha to ``depth`` levels, a sign dasha,
         *     or Kalachakra.
         */
        post: operations["dashas_v1_charts_dashas_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/charts/kp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Kp
         * @description KP analysis; uses the KP preset unless settings or a preset are given.
         */
        post: operations["kp_v1_charts_kp_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/charts/sensitivity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sensitivity
         * @description How many minutes each time-sensitive factor holds before and after the birth time.
         */
        post: operations["sensitivity_v1_charts_sensitivity_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/charts/strengths": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Strengths */
        post: operations["strengths_v1_charts_strengths_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/charts/transits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Transits */
        post: operations["transits_v1_charts_transits_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/charts/yogas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Yogas */
        post: operations["yogas_v1_charts_yogas_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/geo/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Geo Search
         * @description Places by name (GeoNames), most populous first.
         */
        get: operations["geo_search_v1_geo_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/kp/horary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Kp Horary */
        post: operations["kp_horary_v1_kp_horary_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/match": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Match */
        post: operations["match_v1_match_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_v1_me_get"];
        /** Update Me */
        put: operations["update_me_v1_me_put"];
        post?: never;
        /**
         * Delete Me
         * @description Delete the account and everything saved with it.
         */
        delete: operations["delete_me_v1_me_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export
         * @description Everything stored for this account, in one document.
         */
        get: operations["export_v1_me_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/panchanga": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Panchanga */
        post: operations["panchanga_v1_panchanga_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/people": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List People */
        get: operations["list_people_v1_people_get"];
        put?: never;
        /** Create Person */
        post: operations["create_person_v1_people_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/people/{person_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Person */
        get: operations["get_person_v1_people__person_id__get"];
        /** Update Person */
        put: operations["update_person_v1_people__person_id__put"];
        post?: never;
        /** Delete Person */
        delete: operations["delete_person_v1_people__person_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/people/{person_id}/chart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Person Chart */
        post: operations["person_chart_v1_people__person_id__chart_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/people/{person_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Events */
        get: operations["list_events_v1_people__person_id__events_get"];
        put?: never;
        /** Create Event */
        post: operations["create_event_v1_people__person_id__events_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/people/{person_id}/events/{event_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Event */
        delete: operations["delete_event_v1_people__person_id__events__event_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnnualOut */
        AnnualOut: {
            tithi_pravesha: components["schemas"]["TithiPraveshaOut"];
            varshaphal: components["schemas"]["VarshaphalOut"];
        };
        /**
         * AnnualPeriodOut
         * @description A period of an annual-chart dasha; ``lords`` are planet names or "lagna".
         */
        AnnualPeriodOut: {
            /**
             * End
             * Format: date-time
             */
            end: string;
            /** End Jd Ut */
            end_jd_ut: number;
            /** Lords */
            lords: string[];
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /** Start Jd Ut */
            start_jd_ut: number;
        };
        /** AnnualRequest */
        AnnualRequest: {
            birth: components["schemas"]["BirthInput"];
            place?: components["schemas"]["PlaceInput"] | null;
            preset?: components["schemas"]["Preset"] | null;
            settings?: components["schemas"]["Settings"] | null;
            /** Years Completed */
            years_completed: number;
        };
        /** AshtakavargaOut */
        AshtakavargaOut: {
            /** Bav */
            bav: {
                [key: string]: number[];
            };
            /** Graha Pinda */
            graha_pinda: {
                [key: string]: number;
            };
            /** Moon Table */
            moon_table: string;
            /** Rasi Pinda */
            rasi_pinda: {
                [key: string]: number;
            };
            /** Reduced */
            reduced: {
                [key: string]: number[];
            };
            /** Sav */
            sav: number[];
            /** Shodhya Pinda */
            shodhya_pinda: {
                [key: string]: number;
            };
        };
        /**
         * Ayanamsa
         * @enum {string}
         */
        Ayanamsa: "lahiri" | "lahiri_icrc" | "lahiri_1940" | "lahiri_vp285" | "true_chitra" | "true_revati" | "true_pushya" | "raman" | "krishnamurti" | "krishnamurti_vp291" | "yukteshwar" | "jn_bhasin" | "fagan_bradley" | "user";
        /** AyanamsaOut */
        AyanamsaOut: {
            /** Label */
            label: string;
            /** Mean */
            mean: number;
            /** System */
            system: string;
            /** True */
            true: number;
        };
        /**
         * BaladiAvastha
         * @enum {string}
         */
        BaladiAvastha: "bala" | "kumara" | "yuva" | "vriddha" | "mrita";
        /** BhavaBalaOut */
        BhavaBalaOut: {
            /** Adhipati */
            adhipati: number;
            /** Dig */
            dig: number;
            /** Drishti */
            drishti: number;
            /** House */
            house: number;
            lord: components["schemas"]["Body"];
            /** Madhya */
            madhya: number;
            /** Rupas */
            rupas: number;
            /** Total */
            total: number;
        };
        /**
         * BirthInput
         * @description A birth record exactly as written, before any time-zone interpretation.
         */
        BirthInput: {
            /**
             * Local Datetime
             * Format: date-time
             */
            local_datetime: string;
            place: components["schemas"]["PlaceInput"];
            /** @default unknown */
            time_source?: components["schemas"]["BirthTimeSource"];
            /** @default auto */
            time_standard?: components["schemas"]["TimeStandard"];
            /** Uncertainty Minutes */
            uncertainty_minutes?: number | null;
            /** Utc Offset Seconds */
            utc_offset_seconds?: number | null;
            /** Zone */
            zone?: string | null;
        };
        /**
         * BirthTimeSource
         * @description Where the birth time came from; drives the Rodden-style rating.
         * @enum {string}
         */
        BirthTimeSource: "birth_certificate" | "hospital_record" | "family_record" | "memory" | "estimate" | "rectified" | "unknown";
        /**
         * Body
         * @description Bodies in the traditional weekday order, followed by the modern outer planets.
         * @enum {string}
         */
        Body: "sun" | "moon" | "mars" | "mercury" | "jupiter" | "venus" | "saturn" | "rahu" | "ketu" | "uranus" | "neptune" | "pluto";
        /**
         * CalendarOut
         * @description The calendar date of a Hindu day: lunar values at sunrise, Tamil date at sunset.
         */
        CalendarOut: {
            amanta: components["schemas"]["LunarMonthOut"];
            /** Ayana Sidereal */
            ayana_sidereal: string;
            /** Ayana Tropical */
            ayana_tropical: string;
            /** Kali Year */
            kali_year: number;
            /** Kshaya Tithis */
            kshaya_tithis: number[];
            /** Paksha */
            paksha: string;
            /** Paksha Day */
            paksha_day: number;
            /** Purnimanta Adhika */
            purnimanta_adhika: boolean;
            /** Purnimanta Name */
            purnimanta_name: string;
            /** Purnimanta Number */
            purnimanta_number: number;
            /** Ritu */
            ritu: string;
            /** Samvatsara */
            samvatsara: string;
            /** Samvatsara Number */
            samvatsara_number: number;
            /** Shaka Year */
            shaka_year: number;
            /** Tamil Day */
            tamil_day: number;
            /** Tamil Month */
            tamil_month: string;
            /** Tamil Month Number */
            tamil_month_number: number;
            /** Tamil Samvatsara */
            tamil_samvatsara: string;
            /** Vikram Year */
            vikram_year: number;
            /** Vikram Year Kartikadi */
            vikram_year_kartikadi: number;
            /** Vriddhi Tithi */
            vriddhi_tithi: boolean;
        };
        /**
         * Category
         * @enum {string}
         */
        Category: "mahapurusha" | "chandra" | "surya" | "nabhasa" | "raja" | "dhana" | "parivartana" | "viparita" | "neecha_bhanga" | "bhava" | "malika" | "conjunction" | "named" | "dosha" | "birth";
        /** ChartOptions */
        ChartOptions: {
            preset?: components["schemas"]["Preset"] | null;
            settings?: components["schemas"]["Settings"] | null;
        };
        /** ChartRequest */
        ChartRequest: {
            birth: components["schemas"]["BirthInput"];
            preset?: components["schemas"]["Preset"] | null;
            settings?: components["schemas"]["Settings"] | null;
        };
        /** ChartResult */
        ChartResult: {
            ascendant: components["schemas"]["PointOut"];
            ayanamsa: components["schemas"]["AyanamsaOut"];
            birth: components["schemas"]["BirthInput"];
            dashas: components["schemas"]["DashasOut"];
            day: components["schemas"]["DayOut"];
            /** Engine Version */
            engine_version: string;
            ephemeris: components["schemas"]["EphemerisOut"];
            /** Grahas */
            grahas: components["schemas"]["GrahaOut"][];
            houses: components["schemas"]["HousesOut"];
            midheaven: components["schemas"]["PointOut"];
            /** Rodden Rating */
            rodden_rating: string;
            settings: components["schemas"]["Settings"];
            /** Settings Hash */
            settings_hash: string;
            special: components["schemas"]["SpecialPointsOut"];
            time: components["schemas"]["TimeOut"];
            /** Vargas */
            vargas: components["schemas"]["VargaChartOut"][];
        };
        /** CitationOut */
        CitationOut: {
            /** Chapter */
            chapter: number | string | null;
            /** Edition */
            edition: string | null;
            /** Locator */
            locator: string | null;
            /** Text */
            text: string;
            /** Verified */
            verified: boolean;
            /** Verses */
            verses: string | null;
        };
        /**
         * Confidence
         * @enum {string}
         */
        Confidence: "high" | "medium" | "low";
        /** DashaApplicabilityOut */
        DashaApplicabilityOut: {
            /** Applicable */
            applicable: boolean | null;
            /** Rule */
            rule: string;
            /** System */
            system: string;
        };
        /** DashaOut */
        DashaOut: {
            /** Kalachakra Periods */
            kalachakra_periods?: components["schemas"]["KalachakraPeriod"][] | null;
            /** Sign Periods */
            sign_periods?: components["schemas"]["SignPeriod"][] | null;
            /** System */
            system: string;
            table?: components["schemas"]["DashaTableOut"] | null;
        };
        /**
         * DashaPeriodOut
         * @description One dasha period; ``lords`` runs from the mahadasha lord down to this level.
         */
        DashaPeriodOut: {
            /**
             * End
             * Format: date-time
             */
            end: string;
            /** End Jd Ut */
            end_jd_ut: number;
            /** Lords */
            lords: components["schemas"]["Body"][];
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /** Start Jd Ut */
            start_jd_ut: number;
        };
        /** DashaRequest */
        DashaRequest: {
            birth: components["schemas"]["BirthInput"];
            /**
             * Depth
             * @default 2
             */
            depth?: number;
            preset?: components["schemas"]["Preset"] | null;
            settings?: components["schemas"]["Settings"] | null;
            /** System */
            system: string;
        };
        /** DashaTableOut */
        DashaTableOut: {
            /** Balance Years */
            balance_years: number;
            birth_lord: components["schemas"]["Body"];
            /** Label */
            label: string;
            /** Periods */
            periods: components["schemas"]["DashaPeriodOut"][];
            /** System */
            system: string;
            /** Year Days */
            year_days: number;
        };
        /**
         * DashaYear
         * @description Length of the year used to convert dasha periods to calendar dates.
         * @enum {string}
         */
        DashaYear: "sidereal" | "true_sidereal" | "julian" | "tropical" | "savana";
        /** DashasOut */
        DashasOut: {
            /** Applicability */
            applicability: components["schemas"]["DashaApplicabilityOut"][];
            vimshottari: components["schemas"]["DashaTableOut"];
            year: components["schemas"]["DashaYear"];
            /** Year Days */
            year_days: number;
        };
        /** DayOut */
        DayOut: {
            /** Born During Day */
            born_during_day: boolean | null;
            /** Next Sunrise */
            next_sunrise: string | null;
            /** Sunrise */
            sunrise: string | null;
            /** Sunset */
            sunset: string | null;
            /** Weekday */
            weekday: number | null;
        };
        /**
         * Dignity
         * @enum {string}
         */
        Dignity: "exalted" | "moolatrikona" | "own" | "great_friend" | "friend" | "neutral" | "enemy" | "great_enemy" | "debilitated";
        /**
         * Domain
         * @enum {string}
         */
        Domain: "self" | "character" | "intellect" | "wealth" | "career" | "status" | "fame" | "marriage" | "children" | "parents" | "siblings" | "property" | "education" | "health" | "longevity" | "fortune" | "spirituality" | "travel" | "conflict";
        /** DoubleTransit */
        DoubleTransit: {
            /** End Jd Ut */
            end_jd_ut: number;
            /** House */
            house: number;
            /** Sign */
            sign: number;
            /** Start Jd Ut */
            start_jd_ut: number;
        };
        /** EphemerisOut */
        EphemerisOut: {
            /** Jd End */
            jd_end: number;
            /** Jd Start */
            jd_start: number;
            /** Name */
            name: string;
        };
        /** EventIn */
        EventIn: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Description */
            description?: string | null;
            /**
             * Kind
             * @enum {string}
             */
            kind: "marriage" | "divorce" | "child_birth" | "education" | "job" | "promotion" | "job_loss" | "business" | "relocation" | "foreign_travel" | "property" | "illness" | "surgery" | "accident" | "parent_death" | "spouse_death" | "other";
            /**
             * Precision
             * @default day
             * @enum {string}
             */
            precision?: "day" | "month" | "year";
        };
        /** EventOut */
        EventOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Description */
            description?: string | null;
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "marriage" | "divorce" | "child_birth" | "education" | "job" | "promotion" | "job_loss" | "business" | "relocation" | "foreign_travel" | "property" | "illness" | "surgery" | "accident" | "parent_death" | "spouse_death" | "other";
            /**
             * Precision
             * @default day
             * @enum {string}
             */
            precision?: "day" | "month" | "year";
        };
        /** Export */
        Export: {
            /** Events */
            events: {
                [key: string]: components["schemas"]["EventOut"][];
            };
            me: components["schemas"]["Me"];
            /** People */
            people: components["schemas"]["PersonOut"][];
        };
        /** GrahaOut */
        GrahaOut: {
            baladi_avastha: components["schemas"]["BaladiAvastha"];
            body: components["schemas"]["Body"];
            /** Combust */
            combust: boolean;
            /** Degrees In Sign */
            degrees_in_sign: number;
            dignity: components["schemas"]["Dignity"] | null;
            /** Distance Au */
            distance_au: number;
            /** Gandanta */
            gandanta: boolean;
            /** House */
            house: number;
            jagradadi_avastha: components["schemas"]["JagradadiAvastha"] | null;
            kp: components["schemas"]["KpOut"];
            /** Latitude */
            latitude: number;
            nakshatra: components["schemas"]["NakshatraOut"];
            /** Retrograde */
            retrograde: boolean;
            /** Sidereal Longitude */
            sidereal_longitude: number;
            sign: components["schemas"]["Sign"];
            /** Sign Name */
            sign_name: string;
            /** Speed */
            speed: number;
            /** Tropical Longitude */
            tropical_longitude: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HoraryRequest */
        HoraryRequest: {
            /**
             * Moment
             * Format: date-time
             */
            moment: string;
            /** Number */
            number: number;
            place: components["schemas"]["PlaceInput"];
            settings?: components["schemas"]["Settings"] | null;
        };
        /**
         * HouseSystem
         * @enum {string}
         */
        HouseSystem: "whole_sign" | "equal" | "porphyry" | "sripati" | "placidus";
        /** HousesOut */
        HousesOut: {
            /** Cusps */
            cusps: number[];
            /** Fallback */
            fallback: boolean;
            system: components["schemas"]["HouseSystem"];
            /** Whole Sign */
            whole_sign: components["schemas"]["Sign"][];
        };
        /**
         * JagradadiAvastha
         * @enum {string}
         */
        JagradadiAvastha: "jagrat" | "swapna" | "sushupti";
        /**
         * KalachakraPeriod
         * @description A Kalachakra period: ``signs`` from the mahadasha sign down (0 = Aries).
         *
         *     ``pada`` and ``position`` locate the period's sign in its pada's sequence, which
         *     decides the order of its sub-periods.
         */
        KalachakraPeriod: {
            /** End Jd */
            end_jd: number;
            /** Pada */
            pada: number;
            /** Position */
            position: number;
            /** Signs */
            signs: number[];
            /** Start Jd */
            start_jd: number;
        };
        /**
         * Karaka
         * @enum {string}
         */
        Karaka: "atmakaraka" | "amatyakaraka" | "bhratrikaraka" | "matrikaraka" | "pitrikaraka" | "putrakaraka" | "gnatikaraka" | "darakaraka";
        /** KootaOut */
        KootaOut: {
            /** Bride */
            bride: string;
            /** Detail */
            detail: string;
            /** Groom */
            groom: string;
            /** Maximum */
            maximum: number;
            /** Name */
            name: string;
            /** Points */
            points: number;
            /** Sources */
            sources: components["schemas"]["CitationOut"][];
        };
        /**
         * KootaProfile
         * @enum {string}
         */
        KootaProfile: "popular" | "maitreya";
        /**
         * KpChartOut
         * @description KP chart: cusps with their lords, planets, significators, ruling planets.
         */
        KpChartOut: {
            /** Cusps */
            cusps: components["schemas"]["KpCuspOut"][];
            day_lord: components["schemas"]["Body"];
            /** Horary Cusp Jd Ut */
            horary_cusp_jd_ut?: number | null;
            /** Horary Number */
            horary_number?: number | null;
            /** House Significators */
            house_significators: components["schemas"]["Body"][][][];
            /** Planets */
            planets: components["schemas"]["KpPlanetOut"][];
            /** Ruling Planets */
            ruling_planets: components["schemas"]["Body"][];
        };
        /** KpCuspOut */
        KpCuspOut: {
            /** House */
            house: number;
            /** Longitude */
            longitude: number;
            lords: components["schemas"]["KpOut"];
        };
        /** KpOut */
        KpOut: {
            sign_lord: components["schemas"]["Body"];
            star_lord: components["schemas"]["Body"];
            sub_lord: components["schemas"]["Body"];
            sub_sub_lord: components["schemas"]["Body"];
        };
        /** KpPlanetOut */
        KpPlanetOut: {
            body: components["schemas"]["Body"];
            /** House */
            house: number;
            /** Longitude */
            longitude: number;
            lords: components["schemas"]["KpOut"];
            /** Signifies */
            signifies: number[][];
        };
        /** KujaOut */
        KujaOut: {
            /** Cancelled */
            cancelled: string[];
            /** Manglik */
            manglik: boolean;
            /** Present */
            present: string[];
        };
        /**
         * LimbSpanOut
         * @description One tithi, nakshatra, yoga or karana, with its full start and end.
         */
        LimbSpanOut: {
            /**
             * End
             * Format: date-time
             */
            end: string;
            /** End Jd Ut */
            end_jd_ut: number;
            /** Limb */
            limb: string;
            /** Name */
            name: string;
            /** Number */
            number: number;
            /** Paksha */
            paksha?: string | null;
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /** Start Jd Ut */
            start_jd_ut: number;
        };
        /**
         * LunarMonthOut
         * @description An amanta month, from one new moon to the next.
         */
        LunarMonthOut: {
            /** Adhika */
            adhika: boolean;
            /**
             * End
             * Format: date-time
             */
            end: string;
            /** End Jd Ut */
            end_jd_ut: number;
            /** Kshaya Name */
            kshaya_name?: string | null;
            /** Name */
            name: string;
            /** Nija */
            nija: boolean;
            /** Number */
            number: number;
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /** Start Jd Ut */
            start_jd_ut: number;
        };
        /** MatchDoshaOut */
        MatchDoshaOut: {
            /** Cancelled */
            cancelled: boolean;
            /** Exceptions */
            exceptions: string[];
            /** Name */
            name: string;
            /** Present */
            present: boolean;
            /** Sources */
            sources: components["schemas"]["CitationOut"][];
        };
        /**
         * MatchOut
         * @description Marriage matching of two charts (groom first).
         */
        MatchOut: {
            /** Ashtakoota */
            ashtakoota: components["schemas"]["KootaOut"][];
            /** Ashtakoota Total */
            ashtakoota_total: number;
            bride_kuja: components["schemas"]["KujaOut"];
            /** Dashakoota */
            dashakoota: components["schemas"]["PoruthamOut"][];
            /** Dashakoota Agreements */
            dashakoota_agreements: number;
            /** Doshas */
            doshas: components["schemas"]["MatchDoshaOut"][];
            groom_kuja: components["schemas"]["KujaOut"];
            /** Kuja Balanced */
            kuja_balanced: boolean;
            /** Profile */
            profile: string;
            /** Sources */
            sources: components["schemas"]["CitationOut"][];
        };
        /** MatchRequest */
        MatchRequest: {
            bride: components["schemas"]["BirthInput"];
            groom: components["schemas"]["BirthInput"];
            preset?: components["schemas"]["Preset"] | null;
            /** @default popular */
            profile?: components["schemas"]["KootaProfile"];
            settings?: components["schemas"]["Settings"] | null;
        };
        /** Me */
        Me: {
            /** Email */
            email: string | null;
            /** Id */
            id: string;
            /** People */
            people: number;
            /** Research Consent */
            research_consent: boolean;
        };
        /** MeUpdate */
        MeUpdate: {
            /** Research Consent */
            research_consent: boolean;
        };
        /**
         * MoonTable
         * @enum {string}
         */
        MoonTable: "pvr" | "alternative";
        /** NakshatraOut */
        NakshatraOut: {
            /** Deity */
            deity: string;
            /** Fraction Elapsed */
            fraction_elapsed: number;
            /** Index */
            index: number;
            lord: components["schemas"]["Body"];
            /** Name */
            name: string;
            /** Pada */
            pada: number;
        };
        /**
         * NodeType
         * @enum {string}
         */
        NodeType: "mean" | "true";
        /** OfficeBearersOut */
        OfficeBearersOut: {
            /** Candidates */
            candidates: components["schemas"]["Body"][];
            dina_ratri_lord: components["schemas"]["Body"];
            muntha_lord: components["schemas"]["Body"];
            natal_lagna_lord: components["schemas"]["Body"];
            tri_rashi_lord: components["schemas"]["Body"];
            varsha_lagna_lord: components["schemas"]["Body"];
        };
        /**
         * PanchangaOut
         * @description The panchanga of one Hindu day, from sunrise to the next sunrise.
         *
         *     Times are UTC; ``utc_offset_seconds`` gives the local offset at the start of the
         *     civil date. Each limb lists every span overlapping the day.
         */
        PanchangaOut: {
            abhijit: components["schemas"]["PeriodOut"];
            brahma_muhurta: components["schemas"]["PeriodOut"];
            calendar: components["schemas"]["CalendarOut"];
            /** Choghadiyas */
            choghadiyas: components["schemas"]["PeriodOut"][];
            /**
             * Civil Date
             * Format: date
             */
            civil_date: string;
            /** Durmuhurtas */
            durmuhurtas: components["schemas"]["PeriodOut"][];
            /** Horas */
            horas: components["schemas"]["PeriodOut"][];
            /** Kalams */
            kalams: components["schemas"]["PeriodOut"][];
            /** Karanas */
            karanas: components["schemas"]["LimbSpanOut"][];
            /** Moonrise */
            moonrise: string | null;
            /** Moonset */
            moonset: string | null;
            /** Nakshatras */
            nakshatras: components["schemas"]["LimbSpanOut"][];
            /**
             * Next Sunrise
             * Format: date-time
             */
            next_sunrise: string;
            /** Next Sunrise Jd Ut */
            next_sunrise_jd_ut: number;
            place: components["schemas"]["PlaceInput"];
            settings: components["schemas"]["Settings"];
            /**
             * Sunrise
             * Format: date-time
             */
            sunrise: string;
            /** Sunrise Jd Ut */
            sunrise_jd_ut: number;
            /**
             * Sunset
             * Format: date-time
             */
            sunset: string;
            /** Sunset Jd Ut */
            sunset_jd_ut: number;
            /** Tithis */
            tithis: components["schemas"]["LimbSpanOut"][];
            /** Utc Offset Seconds */
            utc_offset_seconds: number;
            /** Vara */
            vara: string;
            vara_lord: components["schemas"]["Body"];
            /** Weekday */
            weekday: number;
            /** Yogas */
            yogas: components["schemas"]["LimbSpanOut"][];
            /** Zone */
            zone: string | null;
        };
        /** PanchangaRequest */
        PanchangaRequest: {
            /**
             * Date
             * Format: date
             */
            date: string;
            place: components["schemas"]["PlaceInput"];
            preset?: components["schemas"]["Preset"] | null;
            settings?: components["schemas"]["Settings"] | null;
            /** Zone */
            zone?: string | null;
        };
        /** PeriodOut */
        PeriodOut: {
            /**
             * End
             * Format: date-time
             */
            end: string;
            /** End Jd Ut */
            end_jd_ut: number;
            lord?: components["schemas"]["Body"] | null;
            /** Name */
            name: string;
            /** Quality */
            quality?: string | null;
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /** Start Jd Ut */
            start_jd_ut: number;
        };
        /** PersonIn */
        PersonIn: {
            birth: components["schemas"]["BirthInput"];
            /** Gender */
            gender?: ("male" | "female") | null;
            /**
             * Guardian Consent
             * @default false
             */
            guardian_consent?: boolean;
            /**
             * Is Minor
             * @default false
             */
            is_minor?: boolean;
            /** Name */
            name: string;
            /** Notes */
            notes?: string | null;
        };
        /** PersonOut */
        PersonOut: {
            birth: components["schemas"]["BirthInput"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Gender */
            gender?: ("male" | "female") | null;
            /**
             * Guardian Consent
             * @default false
             */
            guardian_consent?: boolean;
            /** Id */
            id: string;
            /**
             * Is Minor
             * @default false
             */
            is_minor?: boolean;
            /** Name */
            name: string;
            /** Notes */
            notes?: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** Place */
        Place: {
            /** Admin1 Code */
            admin1_code: string;
            /** Country Code */
            country_code: string;
            /** Geonames Id */
            geonames_id: number;
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /** Name */
            name: string;
            /** Population */
            population: number;
            /** Timezone */
            timezone: string;
        };
        /** PlaceInput */
        PlaceInput: {
            /** Country Code */
            country_code?: string | null;
            /**
             * Elevation M
             * @default 0
             */
            elevation_m?: number;
            /** Geonames Id */
            geonames_id?: number | null;
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /** Name */
            name?: string | null;
        };
        /** PlanetaryWarOut */
        PlanetaryWarOut: {
            /** Planets */
            planets: components["schemas"]["Body"][];
            /** Separation Deg */
            separation_deg: number;
            winner: components["schemas"]["Body"];
        };
        /**
         * PointOut
         * @description A sidereal point with its tropical source value.
         */
        PointOut: {
            /** Degrees In Sign */
            degrees_in_sign: number;
            kp: components["schemas"]["KpOut"];
            nakshatra: components["schemas"]["NakshatraOut"];
            /** Sidereal Longitude */
            sidereal_longitude: number;
            sign: components["schemas"]["Sign"];
            /** Sign Name */
            sign_name: string;
            /** Tropical Longitude */
            tropical_longitude: number;
        };
        /**
         * Polarity
         * @enum {string}
         */
        Polarity: "positive" | "negative" | "mixed";
        /** PoruthamOut */
        PoruthamOut: {
            /** Agrees */
            agrees: boolean;
            /** Detail */
            detail: string;
            /** Name */
            name: string;
            /** Relieved By */
            relieved_by: string | null;
        };
        /**
         * PositionType
         * @enum {string}
         */
        PositionType: "apparent" | "true";
        /**
         * Preset
         * @enum {string}
         */
        Preset: "classic_parashari" | "drik_compatible" | "kp" | "pvr_jhora_style";
        /**
         * Provenance
         * @enum {string}
         */
        Provenance: "classical" | "traditional" | "modern";
        /** SahamOut */
        SahamOut: {
            /** Meaning */
            meaning: string;
            /** Name */
            name: string;
            /** Sensitive */
            sensitive: boolean;
            /** Sidereal Longitude */
            sidereal_longitude: number;
            sign: components["schemas"]["Sign"];
        };
        /**
         * SaturnTransit
         * @enum {string}
         */
        SaturnTransit: "sade_sati" | "ardhashtama" | "ashtama" | "kantaka";
        /**
         * School
         * @enum {string}
         */
        School: "parashari" | "jaimini" | "tajika";
        /** SensitiveFactorOut */
        SensitiveFactorOut: {
            /** Fragile */
            fragile: boolean;
            /** Minutes After */
            minutes_after: number | null;
            /** Minutes Before */
            minutes_before: number | null;
            /** Name */
            name: string;
            /** Value */
            value: string;
        };
        /** SensitivityOut */
        SensitivityOut: {
            /** Factors */
            factors: components["schemas"]["SensitiveFactorOut"][];
            /** Uncertainty Minutes */
            uncertainty_minutes: number;
        };
        /**
         * Settings
         * @description How a chart is calculated. Defaults are the Classic Parashari preset.
         */
        Settings: {
            /** @default pvr */
            ashtakavarga_moon?: components["schemas"]["MoonTable"];
            /** @default lahiri */
            ayanamsa?: components["schemas"]["Ayanamsa"];
            /** @default sripati */
            bhava_system?: components["schemas"]["HouseSystem"];
            /** @default sidereal */
            dasha_year?: components["schemas"]["DashaYear"];
            /**
             * Gulika Convention
             * @default common
             * @enum {string}
             */
            gulika_convention?: "common" | "pvr_book";
            /**
             * Include Outer Planets
             * @default false
             */
            include_outer_planets?: boolean;
            /**
             * Karaka Scheme
             * @default 8
             * @enum {integer}
             */
            karaka_scheme?: 7 | 8;
            /**
             * Node Aspects 5 9
             * @default false
             */
            node_aspects_5_9?: boolean;
            /** @default true */
            node_type?: components["schemas"]["NodeType"];
            /** @default apparent */
            position_type?: components["schemas"]["PositionType"];
            /** @default hindu */
            sunrise?: components["schemas"]["SunriseDefinition"];
            /** User Ayanamsa J2000 */
            user_ayanamsa_j2000?: number | null;
            /** Varga Methods */
            varga_methods?: {
                [key: string]: components["schemas"]["VargaMethod"];
            };
        };
        /**
         * ShadbalaOut
         * @description Shadbala of one planet in virupas (60 virupas = 1 rupa).
         */
        ShadbalaOut: {
            /** Abda */
            abda: number;
            /** Ayana */
            ayana: number;
            body: components["schemas"]["Body"];
            /** Cheshta */
            cheshta: number;
            /** Dig */
            dig: number;
            /** Drekkana */
            drekkana: number;
            /** Drik */
            drik: number;
            /** Hora */
            hora: number;
            /** Ishta Phala */
            ishta_phala: number;
            /** Kala */
            kala: number;
            /** Kashta Phala */
            kashta_phala: number;
            /** Kendradi */
            kendradi: number;
            /** Masa */
            masa: number;
            /** Naisargika */
            naisargika: number;
            /** Nathonnata */
            nathonnata: number;
            /** Ojayugma */
            ojayugma: number;
            /** Paksha */
            paksha: number;
            /** Ratio */
            ratio: number;
            /** Required Rupas */
            required_rupas: number;
            /** Rupas */
            rupas: number;
            /** Saptavargaja */
            saptavargaja: number;
            /** Sthana */
            sthana: number;
            /** Total */
            total: number;
            /** Tribhaga */
            tribhaga: number;
            /** Uchcha */
            uchcha: number;
            /** Vara */
            vara: number;
            /** Yuddha */
            yuddha: number;
        };
        /**
         * Sign
         * @enum {integer}
         */
        Sign: 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11;
        /**
         * SignPeriod
         * @description A sign dasha period; ``signs`` runs from the mahadasha sign down (0 = Aries).
         */
        SignPeriod: {
            /** End Jd */
            end_jd: number;
            /** Signs */
            signs: number[];
            /** Start Jd */
            start_jd: number;
        };
        /** SpecialPointsOut */
        SpecialPointsOut: {
            /** Arudhas */
            arudhas: components["schemas"]["Sign"][];
            bhava_lagna: components["schemas"]["PointOut"] | null;
            ghati_lagna: components["schemas"]["PointOut"] | null;
            hora_lagna: components["schemas"]["PointOut"] | null;
            indu_lagna: components["schemas"]["PointOut"];
            /** Karakas */
            karakas: {
                [key: string]: components["schemas"]["Body"];
            };
            /** Planetary Wars */
            planetary_wars: components["schemas"]["PlanetaryWarOut"][];
            pranapada: components["schemas"]["PointOut"] | null;
            sree_lagna: components["schemas"]["PointOut"];
            /** Upagrahas */
            upagrahas: {
                [key: string]: components["schemas"]["PointOut"];
            };
        };
        /**
         * Status
         * @enum {string}
         */
        Status: "draft" | "reviewed";
        /**
         * Strength
         * @enum {string}
         */
        Strength: "minor" | "moderate" | "major";
        /** StrengthsOut */
        StrengthsOut: {
            ashtakavarga: components["schemas"]["AshtakavargaOut"];
            /** Bhava Bala */
            bhava_bala: components["schemas"]["BhavaBalaOut"][];
            /** Shadbala */
            shadbala: components["schemas"]["ShadbalaOut"][];
            /** Vimshopaka */
            vimshopaka: {
                [key: string]: {
                    [key: string]: number;
                };
            };
        };
        /**
         * SunriseDefinition
         * @enum {string}
         */
        SunriseDefinition: "hindu" | "upper_limb_refraction" | "disc_centre_refraction";
        /** TajikaRelationOut */
        TajikaRelationOut: {
            /** Aspect */
            aspect: string;
            faster: components["schemas"]["Body"];
            /** Friendly */
            friendly: boolean;
            /** Gap */
            gap: number;
            /** Orb */
            orb: number;
            slower: components["schemas"]["Body"];
            /** Yoga */
            yoga: string | null;
        };
        /** TimeInterpretationOut */
        TimeInterpretationOut: {
            /** Label */
            label: string;
            /** Note */
            note?: string | null;
            standard: components["schemas"]["TimeStandard"];
            /**
             * Utc
             * Format: date-time
             */
            utc: string;
            /** Utc Offset Seconds */
            utc_offset_seconds: number;
        };
        /** TimeOut */
        TimeOut: {
            /** Alternatives */
            alternatives: components["schemas"]["TimeInterpretationOut"][];
            /** Ambiguous */
            ambiguous: boolean;
            confidence: components["schemas"]["Confidence"];
            /** Delta T Seconds */
            delta_t_seconds: number;
            interpretation: components["schemas"]["TimeInterpretationOut"];
            /** Jd Tt */
            jd_tt: number;
            /** Jd Ut */
            jd_ut: number;
            /**
             * Local
             * Format: date-time
             */
            local: string;
            /** Warnings */
            warnings: string[];
            /** Zone */
            zone: string | null;
        };
        /**
         * TimeStandard
         * @enum {string}
         */
        TimeStandard: "auto" | "zone" | "lmt" | "bombay_time" | "calcutta_time" | "fixed_offset";
        /** TithiPraveshaOut */
        TithiPraveshaOut: {
            chart: components["schemas"]["ChartResult"];
            /** Elongation */
            elongation: number;
            /** Jd Ut */
            jd_ut: number;
            /**
             * Moment
             * Format: date-time
             */
            moment: string;
            /** Years Completed */
            years_completed: number;
        };
        /** TransitEpisode */
        TransitEpisode: {
            /** End Jd Ut */
            end_jd_ut: number;
            kind: components["schemas"]["SaturnTransit"];
            /** Open End */
            open_end: boolean;
            /** Open Start */
            open_start: boolean;
            /** Spans */
            spans: components["schemas"]["TransitSpan"][];
            /** Start Jd Ut */
            start_jd_ut: number;
        };
        /** TransitRequest */
        TransitRequest: {
            birth: components["schemas"]["BirthInput"];
            /**
             * End
             * Format: date
             */
            end: string;
            preset?: components["schemas"]["Preset"] | null;
            settings?: components["schemas"]["Settings"] | null;
            /**
             * Start
             * Format: date
             */
            start: string;
        };
        /** TransitSpan */
        TransitSpan: {
            /** End Jd Ut */
            end_jd_ut: number;
            /** House */
            house: number;
            /** Sign */
            sign: number;
            /** Start Jd Ut */
            start_jd_ut: number;
        };
        /** TransitsOut */
        TransitsOut: {
            /** Double From Lagna */
            double_from_lagna: components["schemas"]["DoubleTransit"][];
            /** Double From Moon */
            double_from_moon: components["schemas"]["DoubleTransit"][];
            /** Saturn */
            saturn: {
                [key: string]: components["schemas"]["TransitEpisode"][];
            };
        };
        /** UndecidedRuleOut */
        UndecidedRuleOut: {
            /** Id */
            id: string;
            /** Missing */
            missing: string;
            /** Name */
            name: string;
        };
        /**
         * Upagraha
         * @enum {string}
         */
        Upagraha: "dhuma" | "vyatipata" | "parivesha" | "indrachapa" | "upaketu" | "kala" | "mrityu" | "ardhaprahara" | "yamaghantaka" | "gulika" | "mandi";
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VargaChartOut */
        VargaChartOut: {
            ascendant: components["schemas"]["VargaPlacement"];
            /** Division */
            division: number;
            /** Grahas */
            grahas: {
                [key: string]: components["schemas"]["VargaPlacement"];
            };
            method: components["schemas"]["VargaMethod"];
            /** Name */
            name: string;
        };
        /**
         * VargaMethod
         * @enum {string}
         */
        VargaMethod: "parashara" | "parashara_even_reverse" | "parivritti_cyclic" | "parivritti_even_reverse" | "parivritti_alternate" | "jagannatha" | "raman" | "siddhamsa_from_leo";
        /** VargaPlacement */
        VargaPlacement: {
            /** Longitude */
            longitude: number;
            sign: components["schemas"]["Sign"];
        };
        /**
         * VarshaphalOut
         * @description The Tajika annual chart for the year after ``years_completed`` years of life.
         */
        VarshaphalOut: {
            /** By Day */
            by_day: boolean | null;
            chart: components["schemas"]["ChartResult"];
            /**
             * End
             * Format: date-time
             */
            end: string;
            /** End Jd Ut */
            end_jd_ut: number;
            /** Ikkavala */
            ikkavala: boolean;
            /** Induvara */
            induvara: boolean;
            /** Mudda */
            mudda: components["schemas"]["AnnualPeriodOut"][];
            muntha: components["schemas"]["Sign"];
            muntha_lord: components["schemas"]["Body"];
            office_bearers: components["schemas"]["OfficeBearersOut"];
            /** Pancha Vargiya */
            pancha_vargiya: {
                [key: string]: number;
            };
            /** Patyayini */
            patyayini: components["schemas"]["AnnualPeriodOut"][];
            /** Sahams */
            sahams: components["schemas"]["SahamOut"][];
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /** Start Jd Ut */
            start_jd_ut: number;
            /** Tajika */
            tajika: components["schemas"]["TajikaRelationOut"][];
            year_lord: components["schemas"]["Body"];
            /** Year Lord Aspects Lagna */
            year_lord_aspects_lagna: boolean;
            /** Years Completed */
            years_completed: number;
        };
        /**
         * YogaOut
         * @description A knowledge-base rule (yoga or dosha) found in a chart, with its evidence.
         */
        YogaOut: {
            /** Cancel Evidence */
            cancel_evidence: string[];
            category: components["schemas"]["Category"];
            /** Description */
            description: string;
            /** Domains */
            domains: components["schemas"]["Domain"][];
            /** Evidence */
            evidence: string[];
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Participants */
            participants: components["schemas"]["Body"][];
            polarity: components["schemas"]["Polarity"];
            provenance: components["schemas"]["Provenance"];
            school: components["schemas"]["School"];
            /** Sources */
            sources: components["schemas"]["CitationOut"][];
            status: components["schemas"]["Status"];
            strength: components["schemas"]["Strength"];
            /** Summary */
            summary: string;
        };
        /** YogasOut */
        YogasOut: {
            /** Cancelled */
            cancelled: components["schemas"]["YogaOut"][];
            /** Catalogue Size */
            catalogue_size: number;
            /** Present */
            present: components["schemas"]["YogaOut"][];
            /** Undecided */
            undecided: components["schemas"]["UndecidedRuleOut"][];
        };
        /** YogasRequest */
        YogasRequest: {
            birth: components["schemas"]["BirthInput"];
            /** Gender */
            gender?: ("male" | "female") | null;
            /**
             * Include Sensitive
             * @default false
             */
            include_sensitive?: boolean;
            preset?: components["schemas"]["Preset"] | null;
            settings?: components["schemas"]["Settings"] | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    ready_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    chart_v1_charts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChartRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChartResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    annual_v1_charts_annual_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnnualRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnnualOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dashas_v1_charts_dashas_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DashaRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashaOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    kp_v1_charts_kp_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChartRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KpChartOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sensitivity_v1_charts_sensitivity_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChartRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SensitivityOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    strengths_v1_charts_strengths_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChartRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrengthsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    transits_v1_charts_transits_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransitRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransitsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    yogas_v1_charts_yogas_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["YogasRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YogasOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    geo_search_v1_geo_search_get: {
        parameters: {
            query: {
                q: string;
                country?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Place"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    kp_horary_v1_kp_horary_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HoraryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KpChartOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    match_v1_match_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_v1_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
        };
    };
    update_me_v1_me_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MeUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_me_v1_me_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    export_v1_me_export_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Export"];
                };
            };
        };
    };
    panchanga_v1_panchanga_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PanchangaRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PanchangaOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_people_v1_people_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonOut"][];
                };
            };
        };
    };
    create_person_v1_people_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PersonIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_person_v1_people__person_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                person_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_person_v1_people__person_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                person_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PersonIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_person_v1_people__person_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                person_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    person_chart_v1_people__person_id__chart_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                person_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChartOptions"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChartResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_events_v1_people__person_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                person_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_event_v1_people__person_id__events_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                person_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_event_v1_people__person_id__events__event_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                person_id: string;
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
