"""Rectification: recovers the true time of synthetic charts, and checks its input."""

from __future__ import annotations

from datetime import date, datetime, timedelta

import pytest

from jyotish_engine.chart import compute_chart
from jyotish_engine.models import BirthInput, PlaceInput
from jyotish_engine.rectify import EventKind, LifeEvent, best_chart, rectify
from jyotish_engine.rectify.synthetic import synthetic_events

KINDS = [
    EventKind.MARRIAGE,
    EventKind.CHILD_BIRTH,
    EventKind.JOB,
    EventKind.PROMOTION,
    EventKind.PROPERTY,
    EventKind.RELOCATION,
]
CASES = [
    (datetime(1985, 3, 9, 7, 40), 19.0760, 72.8777, 37),
    (datetime(1972, 11, 23, 22, 5), 13.0827, 80.2707, -52),
    (datetime(1991, 8, 2, 14, 20), 28.6139, 77.2090, 18),
    (datetime(1964, 6, 30, 4, 55), 22.5726, 88.3639, -25),
]


def _chart(when: datetime, latitude: float, longitude: float):  # type: ignore[no-untyped-def]
    place = PlaceInput(name="test", latitude=latitude, longitude=longitude)
    return compute_chart(BirthInput(local_datetime=when, place=place))


@pytest.mark.parametrize(("when", "latitude", "longitude", "error"), CASES)
def test_recovers_the_true_time(
    when: datetime, latitude: float, longitude: float, error: int
) -> None:
    """Milestone M9: within two minutes, from events generated by the engine's own rules."""
    events = synthetic_events(_chart(when, latitude, longitude), KINDS)
    recorded = _chart(when + timedelta(minutes=error), latitude, longitude)
    out = rectify(recorded, events, uncertainty_minutes=60, step_seconds=20)
    assert abs(out.candidates[0].offset_minutes + error) <= 2.0
    assert out.candidates[0].share == max(c.share for c in out.candidates)
    assert abs(sum(c.share for c in out.candidates) - 1.0) < 1e-3
    offsets = [c.offset_minutes for c in out.candidates]
    assert all(abs(a - b) >= 2.0 for i, a in enumerate(offsets) for b in offsets[i + 1 :])
    assert len(out.scan) == 2 * 180 + 1
    best = out.candidates[0]
    assert len(best.events) == len(events) and all(len(e.dasha) == 4 for e in best.events)


def test_best_chart_and_priors() -> None:
    chart = _chart(datetime(1985, 3, 9, 7, 40), 19.0760, 72.8777)
    events = synthetic_events(chart, KINDS[:3])
    out = rectify(
        chart, events, uncertainty_minutes=10, priors=["kunda", "navamsa_gender"], gender="male"
    )
    assert set(out.candidates[0].priors) == {"kunda", "navamsa_gender"}
    moved = best_chart(chart, out)
    assert (
        abs((moved.time.jd_ut - chart.time.jd_ut) * 1440 - out.candidates[0].offset_minutes) < 0.01
    )


@pytest.mark.parametrize(
    ("events", "options", "message"),
    [
        ([LifeEvent(EventKind.JOB, date(2015, 1, 1))], {}, "at least two"),
        ([LifeEvent(EventKind.JOB, date(1970, 1, 1))] * 2, {}, "after the birth"),
        ([LifeEvent(EventKind.JOB, date(2015, 1, 1))] * 2, {"uncertainty_minutes": 500}, "window"),
        (
            [LifeEvent(EventKind.JOB, date(2015, 1, 1))] * 2,
            {"priors": ["astrology"]},
            "unknown priors",
        ),
    ],
)
def test_bad_input(events: list[LifeEvent], options: dict[str, object], message: str) -> None:
    chart = _chart(datetime(1985, 3, 9, 7, 40), 19.0760, 72.8777)
    with pytest.raises(ValueError, match=message):
        rectify(chart, events, **options)  # type: ignore[arg-type]
