"""Generate the reading rules in ``knowledge/natal/``, ``dasha/`` and ``transit/``.

Readings are the placement results of the classical texts: each house lord in
each house, each graha in each house and sign, the Moon's nakshatra and the
rising sign. Every result below is written in our own words from the cited
chapters (never a copied translation) and stays a draft until a qualified
Jyotishi reviews it. Test charts are built here with plain sign arithmetic,
independently of the rule language.

    uv run python scripts/generate_readings.py

Edit this script, not the generated files, then re-run it.
"""

from __future__ import annotations

from collections.abc import Callable
from typing import Any

import period_rules
from generate_rule_families import (
    HOUSE_DOMAINS,
    LORDS,
    ROOT,
    SIGNS,
    _dump,
    citation,
    sign_of_house,
    spec,
)

OUT = ROOT / "knowledge"
HEADER = "# Generated by scripts/generate_readings.py; edit the script and re-run it.\n"

GRAHAS = ("sun", "moon", "mars", "mercury", "jupiter", "venus", "saturn", "rahu", "ketu")
POLARITY = {"+": "positive", "-": "negative", "~": "mixed"}
#: Domains of each house for readings; the 8th house (obstacles, chronic illness,
#: hidden matters) is read as health and spirituality rather than longevity.
DOMAINS = {**HOUSE_DOMAINS, 8: ["health", "spirituality"], 12: ["wealth", "spirituality", "travel"]}
PLANET_DOMAIN = {
    "sun": "status",
    "moon": "character",
    "mars": "conflict",
    "mercury": "intellect",
    "jupiter": "fortune",
    "venus": "marriage",
    "saturn": "career",
}
EXALTED = {"sun": 0, "moon": 1, "mars": 9, "mercury": 5, "jupiter": 3, "venus": 11, "saturn": 6}
NAKSHATRAS = [
    "ashwini", "bharani", "krittika", "rohini", "mrigashira", "ardra", "punarvasu",
    "pushya", "ashlesha", "magha", "purva_phalguni", "uttara_phalguni", "hasta",
    "chitra", "swati", "vishakha", "anuradha", "jyeshtha", "mula", "purva_ashadha",
    "uttara_ashadha", "shravana", "dhanishta", "shatabhisha", "purva_bhadrapada",
    "uttara_bhadrapada", "revati",
]  # fmt: skip

# --- Texts ------------------------------------------------------------------------
# Each entry is (polarity, result). Polarity: + positive, - negative, ~ mixed.

#: BPHS, effects of the house lords: LORD_IN_HOUSE[n][m - 1] is the lord of house n in house m.
LORD_IN_HOUSE: dict[int, list[tuple[str, str]]] = {
    1: [
        ("+", "Good health and self-reliance; the native shapes their own fortune."),
        ("+", "Earns and keeps wealth, speaks well, values family and is respected."),
        ("+", "Courageous and enterprising; helped by siblings and friends; gains by own effort."),
        ("+", "Happiness from mother and home; land, vehicles and a settled life."),
        ("+", "Blessed through children and learning; honoured, though quick to anger."),
        (
            "~",
            "Must deal with rivals, debts or illness, yet can defeat opponents; suited to service.",
        ),
        ("~", "Life shaped by partners and dealings with others; much travel."),
        ("-", "Obstacles, sudden changes and interest in hidden subjects; health needs care."),
        ("+", "Fortunate and principled; devoted to dharma, teachers and father."),
        ("+", "Rises by own effort to status and authority; respected for deeds."),
        ("+", "Steady gains, a good income, many friends and success."),
        ("-", "Expenditure, travel or residence abroad; few physical comforts."),
    ],
    2: [
        ("+", "Wealth through own effort; family-minded and eloquent, if blunt."),
        ("+", "Accumulates wealth and family standing; confident, perhaps proud."),
        ("~", "Earnings through courage, communication or siblings; restless with money."),
        ("+", "Wealth from property, mother or family inheritance; fond of comforts."),
        ("+", "Wealth through intelligence, teaching or children; the family prospers."),
        ("~", "Money through service or dealings with rivals; debts or disputes over savings."),
        ("~", "Wealth linked with the spouse or business partners; spends on pleasures."),
        ("~", "Irregular finances with sudden gains and losses; inheritance possible."),
        ("+", "Wealth through fortune and father; learned and generous."),
        ("+", "Earns through career and authority; wealthy and honoured through work."),
        ("+", "Many sources of income; gains through friends and networks."),
        ("-", "Spending exceeds savings; wealth goes to family, travel or religious causes."),
    ],
    3: [
        ("+", "Self-made through courage and initiative; skilled in arts or communication."),
        ("~", "Income through the voice and communication; little appetite for effort."),
        ("+", "Strong bonds with siblings; courageous; fortunate in friends."),
        ("+", "Comforts earned through own effort; siblings support home life."),
        ("+", "Capable children; kind-hearted; siblings are helpful."),
        ("~", "Friction with siblings or neighbours; gains through competition."),
        ("~", "Partnerships through siblings or communication; an energetic spouse."),
        ("-", "Efforts meet obstacles; strained sibling ties; anxiety over risky ventures."),
        ("~", "Fortune grows through effort and journeys; ties with father may be strained."),
        ("+", "A career built on initiative and communication; self-made wealth."),
        ("+", "Gains through siblings, friends and enterprise."),
        ("-", "Spending on siblings or travel; efforts bring limited returns."),
    ],
    4: [
        ("+", "Comforts, property and vehicles; learned; affection from mother."),
        ("+", "Wealth through property, family and mother; comfortable and well-spoken."),
        ("~", "Comforts through effort and courage; generous; property-related travel."),
        ("+", "Owns land, house and vehicles; a happy home and a strong bond with mother."),
        ("+", "Happy and well liked; children and learning bring contentment."),
        ("-", "Disputes over home or property; domestic unrest; strain with mother."),
        ("~", "Learned; comforts come through the spouse; may leave inherited property."),
        ("-", "Little domestic peace or comfort from home; delays over property."),
        ("+", "Fortunate, virtuous and liked; blessings from father and teachers."),
        ("+", "Honours and success in public or administrative life; property through career."),
        ("+", "Gains through property and mother; generous and virtuous."),
        ("-", "Few domestic comforts; living away from home; property losses."),
    ],
    5: [
        ("+", "Learned and devout; happiness through children; creative intelligence."),
        ("+", "Wealth through intelligence and teaching; supports family; famous."),
        ("~", "Attached to siblings; creative courage; children may live at a distance."),
        ("+", "Happy with property and learning; may advise those in authority."),
        ("+", "Children and intelligence prosper; an ethical, creative mind."),
        ("-", "Children may be distant or at odds with the native; friction in progeny matters."),
        ("+", "Honourable and devout; a good spouse; helpful to others."),
        ("-", "Few joys from children or delays; anxiety; interest in mystical learning."),
        ("+", "Children bring fortune; scholarly, famous and respected in the family."),
        ("+", "A Raja yoga: authority, royal favour and many achievements."),
        ("+", "Learned and dear to people; gains through children and speculation."),
        ("-", "Few joys from children, or children living abroad; spiritual leanings."),
    ],
    6: [
        ("~", "Prone to disputes or illness yet wins through effort; can prosper."),
        ("~", "Adventurous; money through service, disputes or lending; family debts."),
        ("~", "Quarrels with siblings; courage wins over rivals."),
        ("-", "Disputes over home or property; changes of residence; strain with mother."),
        ("-", "Fluctuating finances; friction with children or friends."),
        ("+", "Rivals are held in check; enmity with relatives but friendship with outsiders."),
        ("-", "Friction in marriage or partnerships; risk of litigation."),
        ("~", "A Viparita yoga: the troubles of enemies turn to the native's benefit."),
        ("-", "Obstacles to fortune; strain with father; fluctuating work."),
        ("~", "Work in service, law, medicine or competition; conflicts with superiors."),
        ("+", "Gains from competition, rivals or lending; profits through service."),
        ("~", "A Viparita yoga: opposition dissolves, though expenses and travel increase."),
    ],
    7: [
        ("~", "Life centred on relationships and travel; guard against hasty attachments."),
        ("~", "Marriage brings wealth; the spouse is linked with finances."),
        ("~", "Partnerships through siblings or media; marriage may meet early obstacles."),
        ("+", "A spouse who brings comfort and property; a happy home."),
        ("+", "Honoured and virtuous; a spouse connected with learning and children."),
        ("-", "Friction in marriage; the spouse's wellbeing needs care; disputes with partners."),
        ("+", "A happy marriage and gains through partnerships and public dealings."),
        ("-", "Delays or obstacles in marriage; inheritance through the spouse possible."),
        ("+", "The spouse brings good fortune; partnerships across distances."),
        ("+", "Career through partnerships and business; an ambitious, dharmic spouse."),
        ("+", "Gains through the spouse and partners; prosperity after marriage."),
        ("-", "Expenses through the spouse; marriage abroad or across cultures; limited harmony."),
    ],
    8: [
        ("-", "Ups and downs in health and self-confidence; interest in the occult."),
        ("-", "Finances fluctuate; family discord; lost money is hard to regain."),
        ("-", "Discord with siblings; initiative meets obstacles."),
        ("-", "Loss of domestic peace; strain over mother or property; frequent moves."),
        ("-", "Anxiety and worries over children; interest in mystical learning."),
        (
            "+",
            "Sarala yoga: victory over enemies and illness; fearless; prosperity after hardship.",
        ),
        ("-", "Marital difficulties; strain in partnerships; the spouse's wellbeing needs care."),
        ("~", "A resilient constitution; research, occult interests and hidden wealth."),
        ("-", "Obstacles to fortune; strain with father or teachers; unorthodox views."),
        ("-", "Career interruptions; work in research, insurance or crisis fields."),
        ("~", "Gains after early struggles; unexpected income or inheritance."),
        ("~", "Spending on hidden or spiritual matters; losses offset from foreign sources."),
    ],
    9: [
        ("+", "Fortunate, respected and devoted to dharma; blessed by father and teachers."),
        ("+", "Wealth through fortune and father; learned and generous."),
        ("~", "Fortune through siblings, courage and journeys; ties with father may be strained."),
        ("+", "Comforts, property and vehicles through fortune; devoted to mother."),
        ("+", "Fortunate children; fame and merit; an ethical intellect."),
        ("-", "Obstacles to fortune; disputes with relatives; fortune through service."),
        ("+", "Fortune after marriage; a virtuous spouse; gains through partners."),
        ("-", "Obstacles to fortune; strain with father; unconventional beliefs."),
        ("+", "Abundant fortune, virtue and support from relatives; a dharmic life."),
        ("+", "A Raja yoga: high status, honours and fame; career aligned with dharma."),
        ("+", "Great gains and prosperity; charitable; supported by elders."),
        ("~", "Fortune abroad or spent on religious causes; pilgrimages; spiritual pursuits."),
    ],
    10: [
        ("+", "A self-made career; learned and famous; status rises steadily."),
        ("+", "Wealthy, virtuous and honoured; career in family business, finance or speech."),
        ("+", "Career through communication, media or travel; bold and enterprising."),
        ("+", "Happy with property and vehicles; career in land, education or home-based work."),
        ("+", "Career through intelligence, teaching or advisory work; children do well."),
        ("~", "Career in service, health, law or competition; hard-won success against rivals."),
        ("+", "Career through partnerships, business or public dealings; the spouse helps."),
        ("-", "Career obstacles, sudden changes or long gaps; investigative work."),
        ("+", "A Raja yoga: a righteous career, fame and wealth; fortune through work."),
        ("+", "Skilful in all undertakings; a strong career and respect from elders."),
        ("+", "High income from career; many followers; honoured."),
        ("~", "Career abroad or in institutions; work brings expenses; setbacks at home."),
    ],
    11: [
        ("+", "Gains come easily; honest and prosperous; income through personality."),
        ("+", "Many sources of wealth; the family prospers; gains through trade and speech."),
        ("+", "Gains through siblings and effort; skilled in many activities."),
        ("+", "Gains through mother, property or land; pilgrimages; comforts."),
        ("+", "Gains through children, intelligence and speculation."),
        ("~", "Gains through service or competition; disputes over money."),
        ("+", "Gains through the spouse and partners; generous; helpful in-laws."),
        ("~", "Gains through inheritance or sudden sources; unsteady regular income."),
        ("+", "Gains through fortune, father and religious work; righteous."),
        ("+", "Gains through career and authority; honoured by the state."),
        ("+", "Great gains and many friends; income grows year by year."),
        ("~", "Gains from foreign sources, but income drains away; spends on good deeds."),
    ],
    12: [
        ("~", "Spends freely; charming; drawn to travel and spiritual life."),
        ("~", "Savings are hard to keep; spends on family and good causes; pleasant speech."),
        ("-", "Strained ties with siblings; spends on travel and communication."),
        ("-", "Loss of domestic comforts or property; living abroad; strain with mother."),
        ("~", "Expenses on children or children abroad; a spiritual intellect."),
        ("+", "Vimala yoga: expenses controlled and opposition dissolves; frugal and independent."),
        ("-", "Expenses through the spouse; the marriage may bring losses."),
        ("+", "Gains through hidden or foreign sources; spends on spiritual matters."),
        ("~", "Spending on religion and father; fortune abroad; pilgrimages."),
        ("~", "Expenses through work, or a career abroad or in institutions."),
        ("-", "Gains are eroded; spends on friends and elders; foreign income."),
        ("~", "Heavy spending on travel, comforts or spiritual pursuits; generous."),
    ],
}

#: Phaladeepika, results of the grahas in the houses: PLANET_IN_HOUSE[p][h - 1].
PLANET_IN_HOUSE: dict[str, list[tuple[str, str]]] = {
    "sun": [
        ("~", "Confident and energetic with a proud bearing; can be short-tempered."),
        ("~", "Earnings through authority or government; blunt speech; family demands."),
        ("+", "Courageous, enterprising and successful; fame through initiative."),
        ("-", "Restless at home; strained comforts or tension with mother."),
        ("~", "Intelligent and ambitious; worries about children; drawn to politics."),
        ("+", "Victory over rivals, good health and success in administration."),
        ("-", "Marriage and partnerships demand compromise; a proud spouse."),
        ("-", "Obstacles and fluctuating vitality; inheritance matters; research."),
        ("~", "Principled and religious, yet independent of father or teachers."),
        ("+", "Status, authority and fame; success in government or leadership."),
        ("+", "Gains through authority and influential people; a good name."),
        ("-", "Expenses, foreign travel or work in seclusion; low vitality."),
    ],
    "moon": [
        ("~", "Attractive, sensitive and popular; a changeable mind."),
        ("+", "Sweet speech and family support; wealth through public or liquid trades."),
        ("+", "Affectionate siblings, travel and a creative, restless mind."),
        ("+", "A happy home, comforts, vehicles and close ties with mother."),
        ("+", "Imaginative and intelligent; blessed with children."),
        ("-", "Emotional stress, debts or rivals; changeable work."),
        ("+", "A caring, attractive spouse; success in public dealings."),
        ("-", "Emotional turbulence and fluctuating health; mystical interests."),
        ("+", "Religious, fortunate and devoted; pilgrimages; blessings of mother."),
        ("+", "A public-facing career, fame and successful ventures."),
        ("+", "Gains through the public, women and friends."),
        ("-", "Expenses, restless sleep or life abroad; emotional withdrawal."),
    ],
    "mars": [
        ("~", "Energetic, bold and competitive; accident-prone or hot-tempered."),
        ("-", "Harsh speech and family discord; earnings through land or engineering."),
        ("+", "Courageous and victorious; wealth through effort."),
        ("-", "Disturbed domestic peace; property disputes; strain with mother."),
        ("-", "A sharp but impulsive intellect; worries through children; risky speculation."),
        ("+", "Victory over enemies; success in competition, the army or surgery."),
        ("-", "Tension in marriage; a strong-willed spouse; disputes with partners."),
        ("-", "Accidents, surgery or sudden events; disputes over inheritance."),
        ("~", "Strained ties with father or teachers; fortune through courage."),
        ("+", "A commanding career in leadership, engineering, police or the military."),
        ("+", "Gains through land, siblings and bold ventures."),
        ("-", "Expenses and losses through conflict; restless sleep."),
    ],
    "mercury": [
        ("+", "Intelligent, witty and youthful; skilled in communication."),
        ("+", "Eloquent; earns through speech, writing, trade or teaching."),
        ("+", "Skilled in writing and commerce; clever siblings."),
        ("+", "Learned; a happy home and a love of study."),
        ("+", "A sharp intellect; success in education and advice; clever children."),
        ("~", "Clever against rivals; work in accounts, analysis or service; nervous strain."),
        ("+", "A youthful, intelligent spouse; success in trade and partnership."),
        ("~", "Research and occult learning; anxieties about speech or nerves."),
        ("+", "Learned in scripture or law; fortunate through study and teaching."),
        ("+", "A career in commerce, writing or advisory work; recognition."),
        ("+", "Gains through intellect, trade and friends."),
        ("-", "Expenses through learning or travel; scattered thinking."),
    ],
    "jupiter": [
        ("+", "Wise, respected and well built; a counsellor of good conduct."),
        ("+", "Wealthy, eloquent and learned; a prosperous family."),
        ("~", "Supportive siblings but modest initiative; success through advice."),
        ("+", "Happiness, comforts, property and vehicles; a learned mother."),
        ("+", "Wise and blessed with children; success in education and counsel."),
        ("~", "Overcomes rivals through wisdom, though debts or inertia may trouble."),
        ("+", "A virtuous, learned spouse; a happy marriage and profitable partnerships."),
        ("~", "Wisdom in hidden matters and inheritance; modest material gains."),
        ("+", "Highly fortunate and devoted to dharma; a respected teacher or guide."),
        ("+", "An honoured career in law, teaching or administration."),
        ("+", "Great gains, many friends and a prosperous life."),
        ("~", "Spending on religious or charitable causes; spiritual inclinations."),
    ],
    "venus": [
        ("+", "Attractive, charming and artistic; a comfortable life."),
        ("+", "Wealth, sweet speech, fine food and a harmonious family."),
        ("~", "Artistic siblings; talent in arts and media; limited courage."),
        ("+", "Comforts, vehicles, a beautiful home and a loving mother."),
        ("+", "Creative and romantic; blessed with children; success in the arts."),
        ("-", "Trouble through relationships or indulgence; health needs moderation."),
        ("~", "An attractive spouse and strong passions; partnerships prosper."),
        ("~", "Wealth through the spouse or inheritance; hidden pleasures."),
        ("+", "Fortunate, religious and comfortable; blessings through spouse and father."),
        ("+", "A career in arts, beauty, luxury or diplomacy; fame and comforts."),
        ("+", "Gains through the arts, luxury goods and women."),
        ("+", "Enjoys comforts and pleasures; spends on enjoyment."),
    ],
    "saturn": [
        ("-", "Serious, reserved and hard-working; early hardship and a slow rise."),
        ("-", "Harsh speech, slow accumulation of wealth and family burdens."),
        ("+", "Courageous and persistent; success through sustained effort."),
        ("-", "Domestic unhappiness or old property; strain with mother."),
        ("-", "Delays or worries concerning children; a serious intellect."),
        ("+", "Defeats rivals; good health through discipline; success in service."),
        ("-", "Delayed marriage or an older, serious spouse; partnerships need patience."),
        ("~", "Endurance through chronic difficulties; research and perseverance."),
        ("~", "Unorthodox beliefs; strain with father; fortune after hard work."),
        ("+", "A career built on discipline and service; authority after struggle."),
        ("+", "Steady long-term gains and loyal associates."),
        ("-", "Expenses, isolation or work in institutions or abroad."),
    ],
    "rahu": [
        ("~", "An unconventional, ambitious personality; restlessness; foreign influences."),
        ("-", "Unusual speech or habits; wealth from unconventional sources; family tension."),
        ("+", "Bold and enterprising; success in media, technology or risk-taking."),
        ("-", "A restless home life or living abroad; strain with mother."),
        ("-", "An unconventional intellect; worries through children; speculative swings."),
        ("+", "Victory over rivals; success in service and healing professions."),
        ("-", "A spouse from another background; partnerships with outsiders; marital strain."),
        ("-", "Sudden events and occult interests; hidden gains and losses."),
        ("-", "Unorthodox beliefs and foreign travel; strain with father or teachers."),
        ("+", "An ambitious career in foreign, political or technological fields."),
        ("+", "Large gains through networks, foreign sources and technology."),
        ("-", "Foreign travel or residence, expenses and restless sleep."),
    ],
    "ketu": [
        ("~", "Introspective, spiritual and detached; health needs care."),
        ("-", "Detachment from family; irregular finances; blunt speech."),
        ("+", "Courage and inner strength; success through effort."),
        ("-", "Detached from home comforts; changes of residence."),
        ("~", "An intuitive, spiritual intellect; concerns about children."),
        ("+", "Victory over rivals; healing abilities; discipline in health."),
        ("-", "Detached or unusual partnerships; strain in marriage."),
        ("~", "Occult insight and research; sudden events."),
        ("~", "Philosophical and spiritual; unconventional religious views."),
        ("~", "An unusual career path and technical skill; detachment from status."),
        ("+", "Gains through technical or spiritual work; desires fulfilled."),
        ("+", "Spiritual liberation, retreat and journeys to distant lands."),
    ],
}

#: Brihat Jataka, the grahas in the signs: PLANET_IN_SIGN[p][sign].
PLANET_IN_SIGN: dict[str, list[tuple[str, str]]] = {
    "sun": [
        ("+", "Exalted: famous, bold and energetic; a leader who travels widely."),
        ("~", "Patient and fond of comforts and music; earns through trade."),
        ("+", "Learned, eloquent and prosperous; skilled with letters and numbers."),
        ("-", "Sensitive yet stubborn; financial ups and downs; works for others."),
        ("+", "Own sign: strong, steadfast and dignified; natural authority."),
        ("+", "Scholarly and gentle; skilled in writing and the arts."),
        ("-", "Debilitated: setbacks in status, dependence on others, disputes."),
        ("~", "Bold and forceful; skilled in medicine or weapons; can be harsh."),
        ("+", "Respected, wealthy and devout; honoured by the wise."),
        ("-", "Hard-working but slow to gain; reserved; much travel."),
        ("-", "Stubborn and unsettled; financial strain; works for others."),
        ("+", "Gains through trade over water or foreign goods; peaceful and liked."),
    ],
    "moon": [
        ("~", "Energetic, impulsive and fond of travel; quick to act and to anger."),
        ("+", "Exalted: handsome, generous, steady and happy; a good position."),
        ("+", "Witty, playful and sociable; skilled in letters and humour."),
        ("+", "Own sign: wise, kind and home-loving; many friends; prosperous."),
        ("~", "Bold, proud and generous; mental stress; loyal to mother."),
        ("+", "Modest, graceful and well-spoken; skilled in arts and scripture."),
        ("+", "Devoted and learned; prosperous through trade; respects the virtuous."),
        ("-", "Debilitated: intense and secretive; emotional turmoil; distance from family."),
        ("+", "Eloquent, generous and virtuous; inherits wealth."),
        ("~", "Devoted to family and fond of enjoyment; indifferent to others."),
        ("~", "Idealistic and humanitarian, but unsteady in wealth and effort."),
        ("+", "Learned, grateful and handsome; gains through the sea or foreign lands."),
    ],
    "mars": [
        ("+", "Own sign: courageous, commanding and prosperous; a leader who travels."),
        ("~", "Fond of comforts; many friends; friction in relationships."),
        ("~", "Skilled in many arts; bold but restless."),
        ("-", "Debilitated: unsteady and dependent; trouble at home."),
        ("~", "Strong-willed and ambitious; fond of open country."),
        ("~", "Respected and skilled in crafts; a hard worker who avoids conflict."),
        ("~", "Fond of travel and talk; seeks partners; spends lavishly."),
        ("+", "Own sign: energetic, fearless and strategic; wealth through trade."),
        ("+", "A disciplined leader or official with strong convictions."),
        ("+", "Exalted: prosperous, influential and victorious; a commander."),
        ("-", "Restless and argumentative; money is hard to keep."),
        ("-", "Few friends; unsettled; defers to others; away from home."),
    ],
    "mercury": [
        ("~", "Clever but quarrelsome; skilled in writing; fond of risk."),
        ("+", "Prosperous and charitable; a skilled speaker and teacher."),
        ("+", "Own sign: eloquent, learned and skilled in arts and sciences."),
        ("~", "Earns abroad or through liquid trades; talkative; fond of music."),
        ("~", "Clever and ambitious in speech, but short of wealth."),
        ("+", "Exalted: learned, eloquent and virtuous; skilled in writing."),
        ("+", "Skilled in business and the arts; devoted; spends freely."),
        ("~", "Secretive and skilled in research; prone to strain."),
        ("+", "Respected by those in power; learned and generous; a skilled adviser."),
        ("-", "Works for others; practical and hard-working; debts."),
        ("~", "Innovative ideas; works for others; quarrelsome."),
        ("-", "Debilitated: dreamy, with scattered learning; serves others."),
    ],
    "jupiter": [
        ("+", "A leader, prosperous and influential; fond of debate."),
        ("+", "Prosperous, healthy and handsome; charitable; fond of ornaments."),
        ("+", "Learned, eloquent and well dressed; a counsellor."),
        ("+", "Exalted: prosperous, wise, famous and devout; a high position."),
        ("+", "Commanding, firm and respected; first among peers."),
        ("+", "Wise, skilled and prosperous through intellect."),
        ("+", "Intelligent; prosperous through trade; many friends."),
        ("~", "Learned in scripture and the occult; stubborn."),
        ("+", "Own sign: a preceptor, minister or leader; charitable and respected."),
        ("-", "Debilitated: low fortune and limited means; practical faith."),
        ("~", "Learned and humanitarian, but short of wealth; an adviser."),
        ("+", "Own sign: learned in scripture, fearless and respected; a counsellor."),
    ],
    "venus": [
        ("~", "Passionate and restless in love; spends freely."),
        ("+", "Own sign: prosperous and charitable; artistic; a strong family."),
        ("+", "Prosperous, learned and artistic; fond of music and poetry."),
        ("~", "Sensitive and emotional; timid; prosperous through liquid trades."),
        ("~", "Comfort-loving and proud; gains through women."),
        ("-", "Debilitated: disappointments in love and low fortune."),
        ("+", "Own sign: prosperous through own effort, respected and artistic."),
        ("-", "Quarrelsome and secretive in love; debts."),
        ("+", "Prosperous and respected; a religious, charitable spouse."),
        ("~", "Practical in love; attracted to older partners; modest vitality."),
        ("~", "Unconventional relationships; humanitarian."),
        ("+", "Exalted: learned, prosperous, popular and refined in pleasures."),
    ],
    "saturn": [
        ("-", "Debilitated: wandering, friendless and quarrelsome; ups and downs."),
        ("~", "Frugal and patient; hard work brings slow gains."),
        ("-", "Clever but troubled; debts."),
        ("-", "Emotional burdens; distance from mother; health needs care."),
        ("-", "Conflicts with father or authority; burdened."),
        ("~", "Helpful, practical and skilled; few children."),
        ("+", "Exalted: famous, prosperous and just; a leader of groups."),
        ("-", "Secretive and exposed to danger; hard labour."),
        ("+", "Well behaved; respected through children and learning; a happy old age."),
        ("+", "Own sign: respected, landed and prosperous through persistence."),
        ("+", "Own sign: honest and industrious; gains through groups and service."),
        ("+", "Skilled in crafts, modest and patient; respected in the family."),
    ],
}

#: Brihat Jataka, the Moon's nakshatra at birth.
MOON_NAKSHATRA: list[tuple[str, str]] = [
    ("+", "Fond of ornaments, handsome, skilful, intelligent and popular."),
    ("+", "Determined, truthful, healthy and happy; skilled at work."),
    ("~", "Energetic and famous, but sharp-tongued and quick-tempered."),
    ("+", "Truthful, pure, sweet-spoken, steady and handsome."),
    ("+", "Clever, eloquent and prosperous; fond of travel; a little timid."),
    ("~", "Intense, sharp-minded and restless; prone to mood swings."),
    ("+", "Self-controlled, contented and good-natured; few needs."),
    ("+", "Calm, learned, prosperous, virtuous and devout."),
    ("~", "Shrewd, secretive and persuasive; can be ungrateful."),
    ("+", "Prosperous and industrious; devoted to elders and ancestors."),
    ("+", "Sweet-spoken, generous and charming; fond of travel."),
    ("+", "Popular and happy; earns through learning; fond of comfort."),
    ("+", "Industrious, skilful with the hands and enterprising."),
    ("+", "Attractive and artistic; fond of fine clothes and ornaments."),
    ("+", "Self-controlled, kind and independent; skilled in trade."),
    ("~", "Ambitious, determined and eloquent; competitive."),
    ("+", "Loyal and prosperous; fond of travel and friendship; may live abroad."),
    ("~", "Contented and virtuous with few friends; prone to anger and pride."),
    ("~", "Proud, prosperous and firm-minded; can be harsh."),
    ("+", "Proud and independent; a loyal friend and an agreeable spouse."),
    ("+", "Humble, virtuous, grateful and well liked."),
    ("+", "Learned, prosperous, generous and famous."),
    ("+", "Generous, prosperous and courageous; fond of music."),
    ("~", "Truthful, independent and outspoken; defeats rivals; secretive."),
    ("~", "Anxious but skilful with money; talkative; can be harsh."),
    ("+", "Eloquent, happy and wise; defeats rivals; virtuous."),
    ("+", "Well built, popular, brave, pure and prosperous."),
]

#: The rising sign, as contemporary practice describes its temperament.
LAGNA_SIGN: list[tuple[str, str]] = [
    ("~", "Active, courageous and ambitious; quick to act and quick to anger."),
    ("+", "Patient and steady; fond of comfort and beauty; loyal but stubborn."),
    ("+", "Intellectual, communicative and adaptable; curious and restless."),
    ("~", "Sensitive, caring and family-minded; moods follow circumstances."),
    ("+", "Dignified, generous and authoritative; seeks recognition."),
    ("+", "Analytical, modest and practical; attentive to detail and service."),
    ("+", "Balanced, diplomatic and artistic; seeks harmony and partnership."),
    ("~", "Intense, determined and private; resilient in a crisis."),
    ("+", "Principled, optimistic and learned; drawn to teaching and travel."),
    ("~", "Disciplined, practical and ambitious; rises slowly through hard work."),
    ("~", "Independent, humanitarian and unconventional; values ideas and groups."),
    ("+", "Compassionate, imaginative and spiritual; adaptable and generous."),
]

# --- Families ---------------------------------------------------------------------


def _effects(domains: list[str], entry: tuple[str, str], strength: str) -> dict[str, Any]:
    polarity, summary = entry
    unique = list(dict.fromkeys(domains))
    return {
        "domains": unique,
        "polarity": POLARITY[polarity],
        "strength": strength,
        "summary": summary,
    }


def _document(
    category: str, provenance: str, template: dict[str, Any], instances: list[Any]
) -> dict[str, Any]:
    return {
        "defaults": {"category": category, "school": "parashari", "provenance": provenance},
        "families": [{"template": template, "instances": instances}],
    }


def lord_in_house() -> dict[str, Any]:
    instances = []
    for n, row in LORD_IN_HOUSE.items():
        for m, entry in enumerate(row, start=1):
            lagna = (n + 2 * m) % 12
            planet = LORDS[sign_of_house(lagna, n)]
            rest = sign_of_house(lagna, m % 12 + 1)
            positive = spec(lagna, {planet: sign_of_house(lagna, m)}, rest)
            negative = spec(
                lagna, {planet: sign_of_house(lagna, m % 12 + 1)}, sign_of_house(lagna, m)
            )
            instances.append(
                {
                    "params": {"lord": n, "house": m},
                    "overrides": {"effects": _effects(DOMAINS[n] + DOMAINS[m], entry, "moderate")},
                    "tests": {"positive": [positive], "negative": [negative]},
                }
            )
    return _document(
        "lord_in_house",
        "classical",
        {
            "id": "lord_in_house.l{lord}_h{house}",
            "name": "{lord|ord} lord in the {house|ord} house",
            "description": (
                "The lord of the {lord|ord} house occupies the {house|ord} house from the lagna."
            ),
            "when": "house(lord({lord})) == {house}",
            "participants": "[lord({lord})]",
            "sources": [
                citation(
                    "bphs",
                    edition="santhanam",
                    chapter=24,
                    locator="{lord|ord} lord in the {house|ord} house",
                )
            ],
        },
        instances,
    )


def _place(planet: str, sign: int) -> dict[str, int]:
    return {planet: sign}


def planet_in_house() -> dict[str, Any]:
    instances = []
    for planet, row in PLANET_IN_HOUSE.items():
        for h, entry in enumerate(row, start=1):
            lagna = (GRAHAS.index(planet) + h) % 12
            rest = sign_of_house(lagna, (h + 5) % 12 + 1)
            positive = spec(lagna, _place(planet, sign_of_house(lagna, h)), rest)
            negative = spec(lagna, _place(planet, sign_of_house(lagna, h % 12 + 1)), rest)
            node = planet in ("rahu", "ketu")
            overrides: dict[str, Any] = {"effects": _effects(DOMAINS[h], entry, "moderate")}
            if node:
                overrides["provenance"] = "traditional"
                overrides["sources"] = [
                    citation("popular_practice", locator="Rahu and Ketu in the twelve houses")
                ]
            instances.append(
                {
                    "params": {"planet": planet, "house": h},
                    "overrides": overrides,
                    "tests": {"positive": [positive], "negative": [negative]},
                }
            )
    return _document(
        "planet_in_house",
        "classical",
        {
            "id": "planet_in_house.{planet}_h{house}",
            "name": "{planet|title} in the {house|ord} house",
            "description": "{planet|title} occupies the {house|ord} house from the lagna.",
            "when": "house({planet}) == {house}",
            "participants": "[{planet}]",
            "sources": [
                citation(
                    "phaladeepika",
                    edition="sastri",
                    chapter=8,
                    locator="{planet|title} in the {house|ord} house",
                )
            ],
        },
        instances,
    )


def planet_in_sign() -> dict[str, Any]:
    instances = []
    for planet, row in PLANET_IN_SIGN.items():
        for sign, entry in enumerate(row):
            lagna = (sign + 4) % 12
            rest = (sign + 6) % 12
            dignity = sign in (EXALTED[planet], (EXALTED[planet] + 6) % 12)
            instances.append(
                {
                    "params": {
                        "planet": planet,
                        "sign": SIGNS[sign],
                        "chapter": 17 if planet == "moon" else 18,
                    },
                    "overrides": {
                        "effects": _effects(
                            ["character", PLANET_DOMAIN[planet]],
                            entry,
                            "moderate" if dignity else "minor",
                        )
                    },
                    "tests": {
                        "positive": [spec(lagna, {planet: sign}, rest)],
                        "negative": [spec(lagna, {planet: (sign + 1) % 12}, rest)],
                    },
                }
            )
    return _document(
        "planet_in_sign",
        "classical",
        {
            "id": "planet_in_sign.{planet}_{sign}",
            "name": "{planet|title} in {sign|title}",
            "description": "{planet|title} occupies {sign|title}.",
            "when": "sign({planet}) == {sign}",
            "participants": "[{planet}]",
            "sources": [
                citation(
                    "brihat_jataka",
                    edition="sastri",
                    chapter="{chapter}",
                    locator="{planet|title} in {sign|title}",
                )
            ],
        },
        instances,
    )


def moon_nakshatra() -> dict[str, Any]:
    span = 360.0 / 27
    instances = []
    for index, entry in enumerate(MOON_NAKSHATRA):
        middle = round(index * span + span / 2, 3)
        after = round(((index + 1) % 27) * span + span / 2, 3)
        instances.append(
            {
                "params": {"name": NAKSHATRAS[index], "number": index + 1},
                "overrides": {"effects": _effects(["character"], entry, "minor")},
                "tests": {
                    "positive": [{"lagna": "aries", "moon": middle, "rest": "leo"}],
                    "negative": [{"lagna": "aries", "moon": after, "rest": "leo"}],
                },
            }
        )
    return _document(
        "nakshatra",
        "classical",
        {
            "id": "nakshatra.moon_{name}",
            "name": "Moon in {name|title}",
            "description": "The Moon is in the nakshatra {name|title} (number {number}) at birth.",
            "when": "nakshatra(moon) == {number}",
            "participants": "[moon]",
            "sources": [
                citation(
                    "brihat_jataka", edition="sastri", chapter=16, locator="Moon in {name|title}"
                )
            ],
        },
        instances,
    )


def lagna_sign() -> dict[str, Any]:
    instances = [
        {
            "params": {"sign": SIGNS[sign]},
            "overrides": {"effects": _effects(["self", "character"], entry, "minor")},
            "tests": {
                "positive": [{"lagna": SIGNS[sign], "rest": SIGNS[(sign + 3) % 12]}],
                "negative": [{"lagna": SIGNS[(sign + 1) % 12], "rest": SIGNS[(sign + 3) % 12]}],
            },
        }
        for sign, entry in enumerate(LAGNA_SIGN)
    ]
    return _document(
        "lagna",
        "traditional",
        {
            "id": "lagna.{sign}",
            "name": "{sign|title} rising",
            "description": "{sign|title} is the rising sign (lagna).",
            "when": "sign(lagna) == {sign}",
            "notes": (
                "Temperaments of the rising signs as contemporary practice describes them; the "
                "classical texts describe the signs mostly by body and nature."
            ),
            "sources": [citation("popular_practice", locator="Temperament of each rising sign")],
        },
        instances,
    )


#: (folder under knowledge/, file name, builder)
FILES: list[tuple[str, str, Callable[[], dict[str, Any]]]] = [
    ("natal", "lord_in_house.yaml", lord_in_house),
    ("natal", "planet_in_house.yaml", planet_in_house),
    ("natal", "planet_in_sign.yaml", planet_in_sign),
    ("natal", "nakshatra.yaml", moon_nakshatra),
    ("natal", "lagna.yaml", lagna_sign),
    ("dasha", "houses.yaml", period_rules.dasha_houses),
    ("dasha", "planets.yaml", period_rules.dasha_planets),
    ("dasha", "antardasha.yaml", period_rules.dasha_antardasha),
    ("transit", "gochara.yaml", period_rules.gochara),
    ("transit", "slow.yaml", period_rules.slow_transits),
]


def main() -> None:
    for folder, name, build in FILES:
        document = build()
        (OUT / folder).mkdir(exist_ok=True)
        (OUT / folder / name).write_text(HEADER + _dump(document), encoding="utf-8")
        count = len(document.get("rules", [])) + sum(
            len(f["instances"]) for f in document.get("families", [])
        )
        print(f"wrote {count:3d} rules to knowledge/{folder}/{name}")


if __name__ == "__main__":
    main()
