"""Generate the templated yoga families in ``knowledge/yogas/``.

Families such as the 66 sign exchanges are regular enough to write as one
template plus a parameter list. This script writes those YAML files, including a
positive and a negative test chart for every instance. The test charts are built
here with plain Python (sign arithmetic and a small aspect table), independently of
the rule language, so the rule tests check the rule expressions against a second
implementation.

    uv run python scripts/generate_rule_families.py

Edit this script, not the generated files, then re-run it.
"""

from __future__ import annotations

from collections.abc import Callable, Iterator
from itertools import combinations, product
from pathlib import Path
from typing import Any

import yaml

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "knowledge" / "yogas"
HEADER = "# Generated by scripts/generate_rule_families.py; edit the script and re-run it.\n"

SIGNS = [
    "aries", "taurus", "gemini", "cancer", "leo", "virgo",
    "libra", "scorpio", "sagittarius", "capricorn", "aquarius", "pisces",
]  # fmt: skip
LORDS = [
    "mars", "venus", "mercury", "moon", "sun", "mercury",
    "venus", "mars", "jupiter", "saturn", "saturn", "jupiter",
]  # fmt: skip
SEVEN = ("sun", "moon", "mars", "mercury", "jupiter", "venus", "saturn")
#: Houses aspected by each graha, counted from itself (Parashari graha drishti).
ASPECTS = {
    "sun": (7,),
    "moon": (7,),
    "mars": (4, 7, 8),
    "mercury": (7,),
    "jupiter": (5, 7, 9),
    "venus": (7,),
    "saturn": (3, 7, 10),
}
EXALTATION = {
    "sun": 0,
    "moon": 1,
    "mars": 9,
    "mercury": 5,
    "jupiter": 3,
    "venus": 11,
    "saturn": 6,
}
SIGNIFICATIONS = {
    "sun": "soul, father, authority and vitality",
    "moon": "mind, mother, emotions and the public",
    "mars": "courage, siblings, land and conflict",
    "mercury": "intellect, speech, learning and trade",
    "jupiter": "wisdom, children, teachers and dharma",
    "venus": "spouse, pleasures, arts and comforts",
    "saturn": "discipline, service, hardship and longevity",
}
HOUSE_MATTERS = {
    1: "body, health and standing",
    2: "wealth, family and speech",
    3: "siblings, courage and initiative",
    4: "mother, home, property and comforts",
    5: "children, intelligence and merit",
    6: "enemies, debts and disease",
    7: "spouse and partnerships",
    8: "longevity, obstacles and hidden matters",
    9: "fortune, father and dharma",
    10: "career, status and deeds",
    11: "gains and income",
    12: "expenses, losses and liberation",
}
HOUSE_DOMAINS = {
    1: ["self", "health"],
    2: ["wealth"],
    3: ["siblings", "character"],
    4: ["property", "parents"],
    5: ["children", "intellect"],
    6: ["conflict", "health"],
    7: ["marriage"],
    8: ["longevity"],
    9: ["fortune", "parents"],
    10: ["career", "status"],
    11: ["wealth"],
    12: ["wealth", "spirituality"],
}


def ordinal(n: int) -> str:
    suffix = "th" if 10 <= n % 100 <= 20 else {1: "st", 2: "nd", 3: "rd"}.get(n % 10, "th")
    return f"{n}{suffix}"


def _matters(a: int, b: int) -> str:
    return (
        f"the {ordinal(a)} house ({HOUSE_MATTERS[a]}) and the {ordinal(b)} house "
        f"({HOUSE_MATTERS[b]})"
    )


def lord(lagna: int, house: int) -> str:
    return LORDS[(lagna + house - 1) % 12]


def sign_of_house(lagna: int, house: int) -> int:
    return (lagna + house - 1) % 12


def aspects(planet: str, from_sign: int, to_sign: int) -> bool:
    return any((from_sign + h - 1) % 12 == to_sign for h in ASPECTS[planet])


def associated(a: str, sa: int, b: str, sb: int) -> bool:
    """Conjunction, mutual aspect or exchange of two different planets."""
    if a == b:
        return False
    conj = sa == sb
    mutual = aspects(a, sa, sb) and aspects(b, sb, sa)
    swap = LORDS[sa] == b and LORDS[sb] == a
    return conj or mutual or swap


def spec(lagna: int, placements: dict[str, int], rest: int, **extra: Any) -> dict[str, Any]:
    out: dict[str, Any] = {"lagna": SIGNS[lagna]}
    for planet, sign in placements.items():
        out[planet] = SIGNS[sign] if isinstance(sign, int) else sign
    out["rest"] = SIGNS[rest]
    out.update(extra)
    return out


def citation(text: str, **fields: Any) -> dict[str, Any]:
    return {"text": text, **fields, "verified": False}


# --- Families ---------------------------------------------------------------------


def parivartana() -> dict[str, Any]:
    dusthana = {6, 8, 12}
    instances = []
    for a, b in combinations(range(1, 13), 2):
        if a in dusthana or b in dusthana:
            kind, polarity, strength = "dainya", "negative", "moderate"
            summary = (
                f"The {ordinal(a)} and {ordinal(b)} lords exchange signs, and a dusthana "
                "lord is involved (Dainya Parivartana): struggles, enmity and losses in "
                f"the matters of both houses: {_matters(a, b)}."
            )
        elif 3 in (a, b):
            kind, polarity, strength = "khala", "mixed", "minor"
            summary = (
                f"The {ordinal(a)} and {ordinal(b)} lords exchange signs, and the 3rd lord "
                "is involved (Khala Parivartana): fluctuating fortune, bold or rash conduct, "
                f"and good and bad phases in {_matters(a, b)}."
            )
        else:
            kind, polarity, strength = "maha", "positive", "major"
            summary = (
                f"The {ordinal(a)} and {ordinal(b)} lords exchange signs (Maha Parivartana): "
                "the two houses support each other, bringing prosperity, rank and comforts "
                f"through {_matters(a, b)}."
            )
        lagna = next(L for L in range(12) if lord(L, a) != lord(L, b))
        x, y = lord(lagna, a), lord(lagna, b)
        sa, sb = sign_of_house(lagna, a), sign_of_house(lagna, b)
        rest = next(r for r in range(12) if r not in (sa, sb) and LORDS[r] != x and LORDS[r] != y)
        positive = spec(lagna, {x: sb, y: sa}, rest)
        negative = spec(lagna, {x: sb, y: rest}, rest)
        assert LORDS[sb] == y and LORDS[sa] == x and LORDS[rest] != x
        domains = sorted(set(HOUSE_DOMAINS[a]) | set(HOUSE_DOMAINS[b]))
        instances.append(
            {
                "params": {"a": a, "b": b, "kind": kind},
                "overrides": {
                    "effects": {
                        "domains": domains,
                        "polarity": polarity,
                        "strength": strength,
                        "summary": summary,
                    }
                },
                "tests": {"positive": [positive], "negative": [negative]},
            }
        )
    return {
        "defaults": {"category": "parivartana", "school": "parashari", "provenance": "classical"},
        "families": [
            {
                "template": {
                    "id": "parivartana.{kind}_{a}_{b}",
                    "name": "{kind|title} Parivartana Yoga ({a|ord} and {b|ord} lords)",
                    "description": (
                        "The lords of the {a|ord} and {b|ord} houses occupy each other's "
                        "signs (sign exchange). Phaladeepika names exchanges among the lords "
                        "of houses 1, 2, 4, 5, 7, 9, 10 and 11 Maha yoga, those involving the "
                        "3rd lord Khala yoga, and those involving the lord of the 6th, 8th or "
                        "12th Dainya yoga."
                    ),
                    "when": "exchange(lord({a}), lord({b}))",
                    "participants": "[lord({a}), lord({b})]",
                    "sources": [
                        citation("phaladeepika", edition="sastri", chapter=6),
                        citation("raman_300", locator="Parivartana Yogas"),
                    ],
                },
                "instances": instances,
            }
        ],
    }


def lord_pairs(
    pairs: list[tuple[int, int]],
    rule_id: str,
    name: str,
    description: str,
    summary: Callable[[int, int], str],
    category: str,
    sources: list[dict[str, Any]],
    names: dict[tuple[int, int], str] | None = None,
    domains: list[str] | None = None,
) -> dict[str, Any]:
    instances = []
    for a, b in pairs:
        lagna = next(L for L in range(12) if lord(L, a) != lord(L, b))
        x, y = lord(lagna, a), lord(lagna, b)
        # Positive: the two lords conjoined; also a chart with them opposite each other.
        together = next(s for s in range(12) if LORDS[s] not in (x, y))
        rest = next(
            r
            for r in range(12)
            if r not in (together, (together + 6) % 12) and LORDS[r] not in (x, y)
        )
        positives = [spec(lagna, {x: together, y: together}, rest)]
        assert associated(x, together, y, together)
        opposite = (together + 6) % 12
        if LORDS[opposite] not in (x, y):
            positives.append(spec(lagna, {x: together, y: opposite}, rest))
            assert associated(x, together, y, opposite)
        # Negative: adjacent signs (no graha aspects the 2nd or 12th), no exchange.
        sx = next(
            s
            for s in range(12)
            if LORDS[s] != y and LORDS[(s + 1) % 12] != x and not associated(x, s, y, (s + 1) % 12)
        )
        negative = spec(lagna, {x: sx, y: (sx + 1) % 12}, rest)
        overrides: dict[str, Any] = {}
        if names and (a, b) in names:
            overrides["name"] = names[(a, b)]
        effects = {
            "domains": domains or ["status", "career"],
            "polarity": "positive",
            "strength": "major" if category == "raja" else "moderate",
            "summary": summary(a, b),
        }
        overrides["effects"] = effects
        instances.append(
            {
                "params": {"a": a, "b": b},
                "overrides": overrides,
                "tests": {"positive": positives, "negative": [negative]},
            }
        )
    return {
        "defaults": {"category": category, "school": "parashari", "provenance": "classical"},
        "families": [
            {
                "template": {
                    "id": rule_id,
                    "name": name,
                    "description": description,
                    "when": "lord({a}) != lord({b}) and associated(lord({a}), lord({b}))",
                    "participants": "[lord({a}), lord({b})]",
                    "notes": (
                        "Association means conjunction, mutual graha drishti or sign "
                        "exchange. A single planet owning both houses is not counted here "
                        "(see raja.yogakaraka)."
                    ),
                    "sources": sources,
                },
                "instances": instances,
            }
        ],
    }


def raja_lords() -> dict[str, Any]:
    kendras, trikonas = (1, 4, 7, 10), (1, 5, 9)
    pairs = sorted({tuple(sorted((k, t))) for k in kendras for t in trikonas if k != t})
    return lord_pairs(
        pairs,  # type: ignore[arg-type]
        rule_id="raja.lords_{a}_{b}",
        name="Raja Yoga ({a|ord} and {b|ord} lords)",
        description=(
            "The lords of the {a|ord} and {b|ord} houses, one ruling a kendra and the other "
            "a trikona, are associated by conjunction, mutual aspect or exchange."
        ),
        summary=lambda a, b: (
            f"The {ordinal(a)} and {ordinal(b)} lords join a kendra lord to a trikona lord: "
            "a Parashari Raja yoga promising authority, recognition and success, "
            "especially in the dashas of the two lords."
        ),
        category="raja",
        sources=[
            citation("bphs", edition="santhanam", chapter=39),
            citation(
                "laghu_parashari", edition="raman", locator="Raja yogas of kendra and trikona lords"
            ),
        ],
        names={(9, 10): "Dharma Karmadhipati Yoga (9th and 10th lords)"},
    )


def dhana_lords() -> dict[str, Any]:
    pairs = list(combinations((1, 2, 5, 9, 11), 2))
    return lord_pairs(
        pairs,
        rule_id="dhana.lords_{a}_{b}",
        name="Dhana Yoga ({a|ord} and {b|ord} lords)",
        description=(
            "The lords of the {a|ord} and {b|ord} houses, both among the wealth houses "
            "(1, 2, 5, 9, 11), are associated by conjunction, mutual aspect or exchange."
        ),
        summary=lambda a, b: (
            f"The {ordinal(a)} and {ordinal(b)} lords, both wealth-giving, combine: a Dhana "
            "yoga for earnings and accumulated wealth, active in the dashas of the two lords."
        ),
        category="dhana",
        sources=[
            citation("bphs", edition="santhanam", chapter=41),
            citation("pvr_integrated", locator="Dhana yogas"),
        ],
        domains=["wealth"],
    )


def conjunctions() -> dict[str, Any]:
    families = []
    for size, label, source in (
        (2, "dwigraha", citation("brihat_jataka", edition="sastri", chapter=14)),
        (
            3,
            "trigraha",
            citation(
                "saravali", edition="santhanam", locator="Chapter on three-planet conjunctions"
            ),
        ),
    ):
        instances = []
        for group in combinations(SEVEN, size):
            others = [p for p in SEVEN if p not in group]
            sign, rest = 4, 9
            positive = spec(0, dict.fromkeys(group, sign), rest)
            negative = spec(0, {**dict.fromkeys(group, sign), group[-1]: (sign + 1) % 12}, rest)
            extra = spec(0, {**dict.fromkeys(group, sign), others[0]: sign}, rest)
            names = " and ".join(p.title() for p in group)
            meaning = "; ".join(f"{p.title()}: {SIGNIFICATIONS[p]}" for p in group)
            condition = " and ".join(f"conjunct({group[0]}, {p})" for p in group[1:])
            condition += f" and count(only(companions({group[0]}), seven)) == {size - 1}"
            instances.append(
                {
                    "params": {
                        "key": "_".join(group),
                        "names": names,
                        "condition": condition,
                        "members": "[" + ", ".join(group) + "]",
                    },
                    "overrides": {
                        "effects": {
                            "domains": ["character"],
                            "polarity": "mixed",
                            "strength": "minor",
                            "summary": (
                                f"The significations of the planets blend ({meaning}); "
                                "the outcome depends on their dignity and on the house "
                                "and sign they occupy."
                            ),
                        },
                    },
                    "tests": {"positive": [positive], "negative": [negative, extra]},
                }
            )
        families.append(
            {
                "template": {
                    "id": f"conjunction.{label}_{{key}}",
                    "name": f"{label.title()} Yoga ({{names}})",
                    "description": (
                        "{names} occupy the same sign, with no other of the seven planets "
                        f"there ({label.title()} yoga)."
                    ),
                    "when": "{condition}",
                    "participants": "{members}",
                    "sources": [source],
                },
                "instances": instances,
            }
        )
    return {
        "defaults": {"category": "conjunction", "school": "parashari", "provenance": "classical"},
        "families": families,
    }


def malika() -> dict[str, Any]:
    names = {
        1: "lagna",
        2: "dhana",
        3: "vikrama",
        4: "sukha",
        5: "putra",
        6: "satru",
        7: "kalatra",
        8: "randhra",
        9: "bhagya",
        10: "karma",
        11: "labha",
        12: "vyaya",
    }
    instances = []
    for start, name in names.items():
        chain = {p: (start - 1 + i) % 12 for i, p in enumerate(SEVEN)}
        positive = spec(0, chain, 0)
        broken = {**chain, "saturn": (start - 1 + 7) % 12}
        negative = spec(0, broken, 0)
        polarity = "mixed" if start in (6, 8, 12) else "positive"
        instances.append(
            {
                "params": {"start": start, "name": name},
                "overrides": {
                    "effects": {
                        "domains": HOUSE_DOMAINS[start],
                        "polarity": polarity,
                        "strength": "moderate",
                        "summary": (
                            f"A chain of planets starting in the {ordinal(start)} house "
                            f"emphasises its matters ({HOUSE_MATTERS[start]}) and gives an "
                            "eventful, energetic life."
                        ),
                    }
                },
                "tests": {"positive": [positive], "negative": [negative]},
            }
        )
    return {
        "defaults": {"category": "malika", "school": "parashari", "provenance": "traditional"},
        "families": [
            {
                "template": {
                    "id": "malika.{name}",
                    "name": "{name|title} Malika Yoga",
                    "description": (
                        "The seven planets occupy seven consecutive houses, one in each, "
                        "starting from the {start|ord} house. The same charts also form the "
                        "Nabhasa yoga of that arc (Nauka, Kuta, Chatra, Chapa or Ardha "
                        "Chandra)."
                    ),
                    "when": "houses_of(seven) == arc({start}, 7)",
                    "participants": "seven",
                    "sources": [citation("raman_300", locator="Malika Yogas")],
                },
                "instances": instances,
            }
        ],
    }


def kala_sarpa() -> dict[str, Any]:
    names = {
        1: "ananta",
        2: "kulika",
        3: "vasuki",
        4: "shankhapala",
        5: "padma",
        6: "mahapadma",
        7: "takshaka",
        8: "karkotaka",
        9: "shankhachuda",
        10: "ghataka",
        11: "vishadhara",
        12: "sheshanaga",
    }
    instances = []
    for house, name in names.items():
        rahu = (house - 1) % 12
        inside = (rahu + 2) % 12
        positive = spec(0, {"rahu": rahu}, inside)
        negative = spec(0, {"rahu": rahu, "saturn": (rahu + 8) % 12}, inside)
        instances.append(
            {
                "params": {"house": house, "name": name},
                "tests": {"positive": [positive], "negative": [negative]},
            }
        )
    generic_tests = {
        "positive": [
            spec(0, {"rahu": 0}, 2),
            spec(3, {"rahu": 5, "sun": 1, "moon": 2}, 3),
        ],
        "negative": [spec(0, {"rahu": 0, "moon": 8}, 2)],
    }
    shared = {
        "effects": {
            "domains": ["fortune"],
            "polarity": "negative",
            "strength": "moderate",
            "summary": (
                "Modern practice associates this with obstacles, delays and sudden "
                "reversals, easing with age; it is not found in the classical texts."
            ),
        },
        "sources": [
            citation(
                "popular_practice",
                locator="Kala Sarpa Yoga as used in contemporary Indian practice",
            )
        ],
        "notes": (
            "Positions are compared by longitude, so a planet in a node's sign counts as "
            "inside only if it lies on the same side of the axis as the others."
        ),
    }
    return {
        "defaults": {"category": "dosha", "school": "parashari", "provenance": "modern"},
        "rules": [
            {
                "id": "dosha.kala_sarpa",
                "name": "Kala Sarpa Yoga",
                "description": (
                    "All seven planets lie on one side of the Rahu-Ketu axis, hemmed in "
                    "between the nodes."
                ),
                "when": "between_nodes(seven)",
                "participants": "[rahu, ketu]",
                **shared,
                "tests": generic_tests,
            }
        ],
        "families": [
            {
                "template": {
                    "id": "dosha.kala_sarpa_{name}",
                    "name": "{name|title} Kala Sarpa Yoga",
                    "description": (
                        "Kala Sarpa Yoga with Rahu in the {house|ord} house; modern authors "
                        "name the twelve types by Rahu's house."
                    ),
                    "when": "between_nodes(seven) and house(rahu) == {house}",
                    "participants": "[rahu, ketu]",
                    **shared,
                },
                "instances": instances,
            }
        ],
    }


def bhava_lords() -> dict[str, Any]:
    names = {
        1: ("avayoga", "negative"),
        2: ("nisswa", "negative"),
        3: ("mrityu", "negative"),
        4: ("kuhu", "negative"),
        5: ("pamara", "negative"),
        6: ("harsha", "positive"),
        7: ("dushkriti", "negative"),
        8: ("sarala", "positive"),
        9: ("nirbhagya", "negative"),
        10: ("duryoga", "negative"),
        11: ("daridra", "negative"),
        12: ("vimala", "positive"),
    }
    good = {
        6: "enemies and illness are overcome; health, happiness and success over rivals",
        8: "long life, fearlessness, learning and prosperity",
        12: "frugality, good conduct, independence and a respected life",
    }
    instances = []
    for house, (name, polarity) in names.items():
        lagna = 0
        planet = lord(lagna, house)
        positive = spec(lagna, {planet: sign_of_house(lagna, 8)}, sign_of_house(lagna, 3))
        negative = spec(lagna, {planet: sign_of_house(lagna, 1)}, sign_of_house(lagna, 3))
        if house in good:
            summary = (
                f"The {ordinal(house)} lord in a dusthana is a Viparita Raja yoga: {good[house]}."
            )
            category, strength = "viparita", "moderate"
        else:
            summary = (
                f"The {ordinal(house)} lord in a dusthana weakens the {ordinal(house)} house: "
                f"setbacks in {HOUSE_MATTERS[house]}."
            )
            category, strength = "bhava", "moderate"
        instances.append(
            {
                "params": {"house": house, "name": name},
                "overrides": {
                    "category": category,
                    "effects": {
                        "domains": HOUSE_DOMAINS[house],
                        "polarity": polarity,
                        "strength": strength,
                        "summary": summary,
                    },
                },
                "tests": {"positive": [positive], "negative": [negative]},
            }
        )
    return {
        "defaults": {"category": "bhava", "school": "parashari", "provenance": "classical"},
        "families": [
            {
                "template": {
                    "id": "bhava.{name}",
                    "name": "{name|title} Yoga",
                    "description": (
                        "The lord of the {house|ord} house occupies the 6th, 8th or 12th house "
                        "from the lagna."
                    ),
                    "when": "house(lord({house})) in dusthanas",
                    "participants": "[lord({house})]",
                    "notes": (
                        "Phaladeepika names one yoga for each house lord in a dusthana; those "
                        "of the 6th, 8th and 12th lords (Harsha, Sarala, Vimala) are the "
                        "Viparita Raja yogas. Raman reads Harsha, Sarala and Vimala more "
                        "narrowly (the lord in its own house)."
                    ),
                    "sources": [
                        citation("phaladeepika", edition="sastri", chapter=6),
                        citation("raman_300", locator="{name|title} Yoga"),
                    ],
                },
                "instances": instances,
            }
        ],
    }


def _kendra_from(sign: int, ref: int) -> bool:
    return (sign - ref) % 12 in (0, 3, 6, 9)


def _neecha_cancelled(planet: str, lagna: int, signs: dict[str, int]) -> bool:
    """Independent statement of the cancellation conditions used by the rule."""
    here = signs[planet]
    dispositor = LORDS[here]
    exaltation_lord = LORDS[EXALTATION[planet]]
    exalted_here = [p for p in SEVEN if EXALTATION[p] == here]
    moon = signs["moon"]
    for p in [dispositor, exaltation_lord, *exalted_here]:
        if p == planet:
            continue
        if _kendra_from(signs[p], lagna) or (p != "moon" and _kendra_from(signs[p], moon)):
            return True
    if dispositor != planet and aspects(dispositor, signs[dispositor], here):
        return True
    return LORDS[signs[dispositor]] == planet and dispositor != planet


def neecha_bhanga() -> dict[str, Any]:
    instances = []
    for planet in SEVEN:
        debility = (EXALTATION[planet] + 6) % 12
        dispositor = LORDS[debility]
        found_positive = found_negative = None
        for lagna, rest, moon in product(range(12), repeat=3):
            signs = dict.fromkeys(SEVEN, rest)
            signs["moon"] = moon
            signs[planet] = debility
            placed = {planet: debility} if planet == "moon" else {planet: debility, "moon": moon}
            if _neecha_cancelled(planet, lagna, signs):
                if found_positive is None and _kendra_from(signs[dispositor], lagna):
                    found_positive = spec(lagna, placed, rest)
            elif found_negative is None:
                found_negative = spec(lagna, placed, rest)
        assert found_positive and found_negative, planet
        instances.append(
            {
                "params": {"planet": planet},
                "tests": {"positive": [found_positive], "negative": [found_negative]},
            }
        )
    return {
        "defaults": {"category": "neecha_bhanga", "school": "parashari", "provenance": "classical"},
        "families": [
            {
                "template": {
                    "id": "neecha_bhanga.{planet}",
                    "name": "Neecha Bhanga Raja Yoga ({planet|title})",
                    "description": (
                        "{planet|title} is debilitated, but the debility is cancelled: the lord "
                        "of its sign, the lord of its exaltation sign, or a planet exalted in "
                        "that sign is in a kendra from the lagna or the Moon (the Moon itself "
                        "counts from the lagna only); or the lord of its sign aspects it; or "
                        "it exchanges signs with that lord."
                    ),
                    "when": (
                        "debilitated({planet}) and ("
                        "any(x in without([dispositor({planet}), exaltation_lord({planet})], "
                        "[{planet}]): in_kendra(x) or (x != moon and in_kendra(x, moon))) "
                        "or any(x in exalted_in(sign({planet})): "
                        "in_kendra(x) or (x != moon and in_kendra(x, moon))) "
                        "or aspects(dispositor({planet}), {planet}) "
                        "or exchange({planet}, dispositor({planet})))"
                    ),
                    "participants": "[{planet}, dispositor({planet})]",
                    "effects": {
                        "domains": ["status", "career"],
                        "polarity": "positive",
                        "strength": "major",
                        "summary": (
                            "The fall of {planet|title} is redeemed: after early setbacks in "
                            "its matters the native rises, often to a position of authority."
                        ),
                    },
                    "notes": (
                        "Texts list further cancellations (for example the planet exalted "
                        "in the navamsa); only the conditions above are encoded."
                    ),
                    "sources": [
                        citation("phaladeepika", edition="sastri", chapter=7),
                        citation("raman_300", locator="Neechabhanga Raja Yoga"),
                    ],
                },
                "instances": instances,
            }
        ],
    }


def _dump(document: dict[str, Any]) -> str:
    class Dumper(yaml.SafeDumper):
        pass

    def represent_dict(dumper: yaml.SafeDumper, data: dict[str, Any]) -> yaml.Node:
        flow = "lagna" in data or set(data) <= {"text", "edition", "chapter", "locator", "verified"}
        return dumper.represent_mapping("tag:yaml.org,2002:map", data.items(), flow_style=flow)

    def represent_list(dumper: yaml.SafeDumper, data: list[Any]) -> yaml.Node:
        flow = all(isinstance(x, (str, int)) and len(str(x)) < 20 for x in data)
        return dumper.represent_sequence("tag:yaml.org,2002:seq", data, flow_style=flow)

    Dumper.add_representer(dict, represent_dict)
    Dumper.add_representer(list, represent_list)
    return yaml.dump(document, Dumper=Dumper, sort_keys=False, width=100, allow_unicode=True)


def main() -> None:
    files: Iterator[tuple[str, Callable[[], dict[str, Any]]]] = iter(
        [
            ("parivartana.yaml", parivartana),
            ("raja_lords.yaml", raja_lords),
            ("dhana_lords.yaml", dhana_lords),
            ("conjunctions.yaml", conjunctions),
            ("malika.yaml", malika),
            ("kala_sarpa.yaml", kala_sarpa),
            ("bhava_lords.yaml", bhava_lords),
            ("neecha_bhanga.yaml", neecha_bhanga),
        ]
    )
    for name, build in files:
        document = build()
        (OUT / name).write_text(HEADER + _dump(document), encoding="utf-8")
        count = len(document.get("rules", [])) + sum(
            len(f["instances"]) for f in document.get("families", [])
        )
        print(f"wrote {count:3d} rules to knowledge/yogas/{name}")


if __name__ == "__main__":
    main()
